import React from'react'
import{View,Text,StyleSheet}from'react-native'
import{LinearGradient}from'expo-linear-gradient'
import{router}from'expo-router'
import{Globe2,ChevronRight,Trophy,Dog,Clapperboard,Music2,CalendarDays}from'lucide-react-native'
import{SensoryPressable}from'@/components/v6/SensoryPressable'
import{useV8World}from'@/hooks/v8/useV8World'
import{V8_WORLD_STOPS,V8_COMPANIONS}from'@/constants/v8'
import{Colors,FontWeight,Shadow}from'@/constants/theme'
export function V8WorldCard(){const{state}=useV8World();const stop=[...V8_WORLD_STOPS].reverse().find(x=>state.worldClaimed.includes(x.id))??V8_WORLD_STOPS[0];const comp=V8_COMPANIONS.find(x=>x.id===state.companionId);return <LinearGradient colors={['#07111F','#0F3D56','#155E75']} style={s.card}><View style={s.head}><View style={s.icon}><Globe2 size={18} color="#67E8F9"/></View><View style={{flex:1}}><Text style={s.kicker}>WORLD & IDENTITY</Text><Text style={s.title}>{stop.name} · {stop.subtitle}</Text></View><SensoryPressable event="selection" onPress={()=>router.push('/modals/world' as any)} style={s.go}><ChevronRight size={18} color="#fff"/></SensoryPressable></View><View style={s.row}><SensoryPressable event="selection" onPress={()=>router.push('/modals/profile-card' as any)} style={s.tile}><Trophy size={17} color="#FBBF24"/><Text style={s.tileTitle}>Ma carte</Text><Text style={s.tileSub}>Style & partage</Text></SensoryPressable><SensoryPressable event="selection" onPress={()=>router.push('/modals/companion-studio' as any)} style={s.tile}><Dog size={17} color="#A5B4FC"/><Text style={s.tileTitle}>{comp?.name??'Compagnon'}</Text><Text style={s.tileSub}>Personnaliser</Text></SensoryPressable><SensoryPressable event="selection" onPress={()=>router.push('/modals/trophy-room' as any)} style={s.tile}><Trophy size={17} color="#34D399"/><Text style={s.tileTitle}>Trophées</Text><Text style={s.tileSub}>{state.pinnedTrophies.length} exposés</Text></SensoryPressable><SensoryPressable event="selection" onPress={()=>router.push('/modals/story-builder' as any)} style={s.tile}><Clapperboard size={17} color="#FB7185"/><Text style={s.tileTitle}>Stories</Text><Text style={s.tileSub}>Créer un souvenir</Text></SensoryPressable></View><View style={s.footer}><SensoryPressable event="selection" onPress={()=>router.push('/modals/music-space' as any)} style={s.footerBtn}><Music2 size={14} color="#F472B6"/><Text style={s.footerText}>Music Space</Text></SensoryPressable><SensoryPressable event="selection" onPress={()=>router.push('/modals/season' as any)} style={s.footerBtn}><CalendarDays size={14} color="#C4B5FD"/><Text style={s.footerText}>Season 08</Text></SensoryPressable></View></LinearGradient>}
const s=StyleSheet.create({card:{marginHorizontal:16,marginTop:10,borderRadius:24,padding:16,...Shadow.md},head:{flexDirection:'row',alignItems:'center',gap:10},icon:{width:38,height:38,borderRadius:14,backgroundColor:'rgba(103,232,249,.12)',alignItems:'center',justifyContent:'center'},kicker:{fontSize:8,color:'#67E8F9',fontWeight:FontWeight.extrabold,letterSpacing:1.3},title:{fontSize:15,color:'#fff',fontWeight:FontWeight.extrabold,marginTop:2},go:{width:34,height:34,borderRadius:12,backgroundColor:'rgba(255,255,255,.09)',alignItems:'center',justifyContent:'center'},row:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:14},tile:{width:'48%',borderRadius:16,padding:11,backgroundColor:'rgba(255,255,255,.07)',borderWidth:1,borderColor:'rgba(255,255,255,.08)'},tileTitle:{fontSize:11,color:'#fff',fontWeight:FontWeight.extrabold,marginTop:8},tileSub:{fontSize:8,color:'#94A3B8',fontWeight:FontWeight.bold,marginTop:2},footer:{flexDirection:'row',gap:8,marginTop:10},footerBtn:{flex:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6,paddingVertical:9,borderRadius:13,backgroundColor:'rgba(255,255,255,.06)'},footerText:{fontSize:9,color:'#E2E8F0',fontWeight:FontWeight.extrabold}})
