import React,{useEffect}from'react'
import{Modal,View,Text,StyleSheet}from'react-native'
import Animated,{FadeIn,useSharedValue,useAnimatedStyle,withSpring,withTiming,withSequence,withDelay,withRepeat}from'react-native-reanimated'
import{LinearGradient}from'expo-linear-gradient'
import{Trophy,Sparkles,Star}from'lucide-react-native'
import{Colors,FontWeight,Shadow}from'@/constants/theme'
import{useSensoryFeedback}from'@/hooks/useSensoryFeedback'
import{SensoryPressable}from'@/components/v6/SensoryPressable'

const PARTICLES=[[-88,-104],[-48,-132],[0,-145],[52,-126],[92,-88],[-108,-34],[108,-28],[-72,92],[75,96]]
export function RewardBurst({visible,title='Récompense débloquée',subtitle,xp=0,onClose}:{visible:boolean;title?:string;subtitle?:string;xp?:number;onClose:()=>void}){
 const scale=useSharedValue(.55),opacity=useSharedValue(0),ring=useSharedValue(.65),float=useSharedValue(0)
 const{play,prefs}=useSensoryFeedback()
 useEffect(()=>{if(!visible)return;scale.value=prefs.reducedMotion?1:withSpring(1,{damping:9,stiffness:170});opacity.value=withTiming(1,{duration:180});ring.value=prefs.reducedMotion?1:withSequence(withTiming(1.34,{duration:430}),withTiming(1,{duration:240}));float.value=prefs.reducedMotion?0:withRepeat(withSequence(withTiming(-5,{duration:850}),withTiming(0,{duration:850})),-1,true);play('reward')},[visible,prefs.reducedMotion])
 const card=useAnimatedStyle(()=>({opacity:opacity.value,transform:[{scale:scale.value},{translateY:float.value}]}));const halo=useAnimatedStyle(()=>({transform:[{scale:ring.value}],opacity:.24}))
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={s.backdrop}><Animated.View style={[s.halo,halo]}/>{!prefs.reducedMotion&&PARTICLES.map(([x,y],i)=><Animated.View entering={FadeIn.delay(80+i*35).duration(260)} key={i} style={[s.particle,{transform:[{translateX:x},{translateY:y},{rotate:`${i*23}deg`}]}]}><Star size={i%3===0?13:9} color={i%2?'#A5B4FC':'#FBBF24'} fill={i%2?'#A5B4FC':'#FBBF24'}/></Animated.View>)}<Animated.View style={[s.card,card]}><LinearGradient colors={['#0B1430','#315CFF','#7C3AED']} start={{x:0,y:0}} end={{x:1,y:1}} style={s.inner}><View style={s.badge}><LinearGradient colors={['rgba(251,191,36,.24)','rgba(255,255,255,.08)']} style={StyleSheet.absoluteFill}/><Trophy size={38} color="#FBBF24"/><Sparkles size={17} color="#fff" style={s.spark}/></View><Text style={s.kicker}>HYBRID REWARD</Text><Text style={s.title}>{title}</Text>{subtitle?<Text style={s.sub}>{subtitle}</Text>:null}{xp>0?<View style={s.xp}><Text style={s.xpText}>+{xp} XP</Text></View>:null}<SensoryPressable event="selection" style={s.btn} onPress={onClose}><Text style={s.btnText}>Continuer</Text></SensoryPressable></LinearGradient></Animated.View></View></Modal>
}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:'rgba(3,7,18,.78)',alignItems:'center',justifyContent:'center',padding:24},halo:{position:'absolute',width:285,height:285,borderRadius:143,backgroundColor:'#7C3AED'},particle:{position:'absolute',zIndex:2},card:{width:'100%',maxWidth:380,borderRadius:32,...Shadow.lg,zIndex:3},inner:{borderRadius:32,padding:27,alignItems:'center',overflow:'hidden'},badge:{width:90,height:90,borderRadius:29,borderWidth:1,borderColor:'rgba(255,255,255,.18)',alignItems:'center',justifyContent:'center',overflow:'hidden'},spark:{position:'absolute',right:12,top:10},kicker:{fontSize:9,color:'#C4B5FD',fontWeight:FontWeight.extrabold,letterSpacing:1.7,marginTop:16},title:{fontSize:25,color:'#fff',fontWeight:FontWeight.extrabold,textAlign:'center',marginTop:5},sub:{fontSize:12,color:'#D8E1FF',textAlign:'center',lineHeight:18,marginTop:7},xp:{marginTop:14,backgroundColor:'rgba(251,191,36,.16)',borderWidth:1,borderColor:'rgba(251,191,36,.32)',borderRadius:99,paddingHorizontal:16,paddingVertical:8},xpText:{color:'#FBBF24',fontWeight:FontWeight.extrabold},btn:{marginTop:21,backgroundColor:'#fff',borderRadius:16,paddingVertical:13,paddingHorizontal:34,...Shadow.sm},btnText:{color:Colors.textPrimary,fontWeight:FontWeight.extrabold}})
