import React from'react'
import{View,Text,TextInput,TouchableOpacity,StyleSheet}from'react-native'
import{Colors,FontSize,FontWeight,Radius,Spacing}from'@/constants/theme'
import type{SportDefinition,MetricField}from'@/constants/sportCatalog'
export function DynamicSportFields({sport,sessionType,onSessionType,values,onChange}:{sport:SportDefinition;sessionType:string;onSessionType:(v:string)=>void;values:Record<string,any>;onChange:(key:string,v:any)=>void}){return <View style={s.wrap}>
<Text style={s.heading}>Type de séance</Text><View style={s.chips}>{sport.sessionTypes.map(o=><TouchableOpacity key={o.value} onPress={()=>onSessionType(o.value)} style={[s.chip,sessionType===o.value&&{borderColor:sport.color,backgroundColor:sport.color+'14'}]}><Text style={[s.chipText,sessionType===o.value&&{color:sport.color,fontWeight:FontWeight.bold}]}>{o.label}</Text></TouchableOpacity>)}</View>
<Text style={s.heading}>Données {sport.label}</Text><View style={s.grid}>{sport.metrics.map(f=><Metric key={f.key} f={f} value={values[f.key]} onChange={v=>onChange(f.key,v)} color={sport.color}/>)}</View>
<Text style={s.hint}>💡 Le Coach utilisera ces données pour adapter ses conseils et les prochaines séances.</Text>
</View>}
function Metric({f,value,onChange,color}:{f:MetricField;value:any;onChange:(v:any)=>void;color:string}){if(f.type==='boolean')return <TouchableOpacity onPress={()=>onChange(!value)} style={[s.boolean,value&&{borderColor:color,backgroundColor:color+'14'}]}><Text style={s.booleanIcon}>{value?'✓':'○'}</Text><Text style={[s.booleanText,value&&{color}]}>{f.label}</Text></TouchableOpacity>;if(f.type==='select')return <View style={s.full}><Text style={s.label}>{f.label}</Text><View style={s.chips}>{f.options?.map(o=><TouchableOpacity key={o.value} onPress={()=>onChange(o.value)} style={[s.chip,value===o.value&&{borderColor:color,backgroundColor:color+'14'}]}><Text style={[s.chipText,value===o.value&&{color,fontWeight:FontWeight.bold}]}>{o.label}</Text></TouchableOpacity>)}</View></View>;return <View style={s.field}><Text style={s.label}>{f.label}{f.unit?` (${f.unit})`:''}</Text><TextInput value={value==null?'':String(value)} onChangeText={onChange} placeholder={f.placeholder??''} placeholderTextColor={Colors.textTertiary} keyboardType={f.type==='number'?'decimal-pad':'default'} style={s.input}/></View>}
const s=StyleSheet.create({wrap:{gap:12},heading:{fontSize:FontSize.md,fontWeight:FontWeight.bold,color:Colors.textPrimary,marginTop:4},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderColor:Colors.border,borderRadius:Radius.full,paddingHorizontal:10,paddingVertical:8,backgroundColor:Colors.bgCard},chipText:{fontSize:FontSize.sm,color:Colors.textSecondary},grid:{flexDirection:'row',flexWrap:'wrap',gap:9},field:{width:'48%',borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,padding:10,backgroundColor:Colors.bgCard},full:{width:'100%',gap:7},label:{fontSize:FontSize.xs,color:Colors.textSecondary,fontWeight:FontWeight.semibold},input:{fontSize:FontSize.md,color:Colors.textPrimary,paddingTop:7,paddingBottom:2},boolean:{flexDirection:'row',alignItems:'center',gap:8,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,padding:12,backgroundColor:Colors.bgCard},booleanIcon:{fontSize:18},booleanText:{fontSize:FontSize.sm,color:Colors.textPrimary},hint:{fontSize:FontSize.xs,color:Colors.textSecondary,lineHeight:18,backgroundColor:Colors.electricDim,padding:10,borderRadius:Radius.md}})
