import React,{useCallback,useEffect,useMemo,useState}from'react'
import{View,Text,StyleSheet,TouchableOpacity,ScrollView,ActivityIndicator}from'react-native'
import{useSafeAreaInsets}from'react-native-safe-area-context'
import{router,useLocalSearchParams}from'expo-router'
import{ArrowLeft,Radio,MapPin,HeartPulse,Gauge,Music2,MessageCircle,Eye,ShieldCheck}from'lucide-react-native'
import{Colors,FontWeight,Shadow}from'@/constants/theme'
import{LIVE_REACTIONS}from'@/constants/v4'
import{LiveMap}from'@/components/live/LiveMap'
import{Avatar}from'@/components/ui/Avatar'
import{supabase}from'@/lib/supabase'
import{useSession}from'@/hooks/useProfile'
import type{LiveActivity}from'@/types/database'

export default function WatchLive(){
 const{id}=useLocalSearchParams<{id:string}>();const insets=useSafeAreaInsets();const{userId}=useSession();const[live,setLive]=useState<LiveActivity|null>(null);const[points,setPoints]=useState<any[]>([]);const[notes,setNotes]=useState<any[]>([]);const[reactionCounts,setReactionCounts]=useState<Record<string,number>>({});const[loading,setLoading]=useState(true)
 const load=useCallback(async()=>{if(!id)return;setLoading(true);const[{data:l},{data:pts},{data:n},{data:r}]=await Promise.all([supabase.from('live_activities').select('*, profile:profiles!user_id(id,username,avatar_url,is_pro,hybrid_score)').eq('id',id).maybeSingle(),supabase.from('live_points').select('lat,lng,recorded_at').eq('live_activity_id',id).order('recorded_at',{ascending:true}).limit(400),supabase.from('live_notes').select('*').eq('live_activity_id',id).order('created_at',{ascending:false}),supabase.from('live_reactions').select('emoji').eq('live_activity_id',id)]);setLive(l as any);setPoints((pts??[]).map((p:any)=>({latitude:p.lat,longitude:p.lng})));setNotes(n??[]);const c:Record<string,number>={};for(const x of r??[])c[x.emoji]=(c[x.emoji]??0)+1;setReactionCounts(c);setLoading(false)},[id])
 useEffect(()=>{load();if(!id)return;const ch=supabase.channel(`watch-${id}`).on('postgres_changes',{event:'*',schema:'public',table:'live_activities',filter:`id=eq.${id}`},load).on('postgres_changes',{event:'INSERT',schema:'public',table:'live_points',filter:`live_activity_id=eq.${id}`},load).on('postgres_changes',{event:'INSERT',schema:'public',table:'live_notes',filter:`live_activity_id=eq.${id}`},load).on('postgres_changes',{event:'INSERT',schema:'public',table:'live_reactions',filter:`live_activity_id=eq.${id}`},load).subscribe();return()=>{supabase.removeChannel(ch)}},[id,load])
 const react=async(emoji:string)=>{if(!id||!userId)return;await supabase.from('live_reactions').insert({live_activity_id:id,user_id:userId,emoji});setReactionCounts(c=>({...c,[emoji]:(c[emoji]??0)+1}))}
 if(loading)return <View style={s.center}><ActivityIndicator color={Colors.electric}/></View>
 if(!live)return <View style={s.center}><Text style={s.notFound}>Ce Live n’est plus disponible.</Text><TouchableOpacity onPress={()=>router.back()}><Text style={s.link}>Retour</Text></TouchableOpacity></View>
 const p=(live as any).profile;return <View style={[s.root,{paddingTop:insets.top}]}><View style={s.header}><TouchableOpacity style={s.back} onPress={()=>router.back()}><ArrowLeft size={20} color={Colors.textPrimary}/></TouchableOpacity><Avatar uri={p?.avatar_url} username={p?.username??'?'} size={38}/><View style={{flex:1}}><Text style={s.name}>{p?.username??'Athlète'}</Text><View style={s.liveLabel}><View style={s.dot}/><Text style={s.liveText}>EN DIRECT</Text></View></View><ShieldCheck size={19} color="#10B981"/></View><ScrollView contentContainerStyle={{paddingBottom:40}} showsVerticalScrollIndicator={false}>
 <View style={s.map}><LiveMap points={points}/><View style={s.mapBadge}><Eye size={13} color="#fff"/><Text style={s.mapBadgeText}>Position protégée · {live.delayed_minutes??5} min de délai</Text></View></View>
 <View style={s.metrics}><Metric icon={<MapPin size={17} color="#06B6D4"/>} value={`${Number(live.distance_km??0).toFixed(2)} km`} label="Distance"/><Metric icon={<Gauge size={17} color="#F59E0B"/>} value={live.pace_seconds_per_km?pace(live.pace_seconds_per_km):'—'} label="Allure"/><Metric icon={<HeartPulse size={17} color="#FB7185"/>} value={live.heart_rate?`${live.heart_rate}`:'—'} label="FC"/></View>
 {live.current_track?<View style={s.card}><View style={s.cardHead}><Music2 size={19} color="#22C55E"/><Text style={s.cardTitle}>En ce moment</Text></View><Text style={s.trackTitle}>{live.current_track.title}</Text><Text style={s.trackSub}>{live.current_track.artist}</Text></View>:null}
 <View style={s.card}><View style={s.cardHead}><MessageCircle size={19} color="#7C3AED"/><Text style={s.cardTitle}>Journal Live</Text></View>{notes.length?notes.map(n=><View key={n.id} style={s.note}><View style={s.noteDot}/><View style={{flex:1}}><Text style={s.noteAt}>{n.distance_km?`km ${Number(n.distance_km).toFixed(1)} · `:''}{Math.round((n.at_seconds??0)/60)} min</Text><Text style={s.noteText}>{n.text}</Text></View></View>):<Text style={s.empty}>Aucune note pour l’instant.</Text>}</View>
 <View style={s.card}><Text style={s.cardTitle}>Encourager</Text><Text style={s.empty}>Un encouragement rapide, sans distraire l’athlète.</Text><View style={s.reactions}>{LIVE_REACTIONS.map(e=><TouchableOpacity key={e} style={s.reaction} onPress={()=>react(e)}><Text style={s.emoji}>{e}</Text><Text style={s.count}>{reactionCounts[e]??0}</Text></TouchableOpacity>)}</View></View>
 </ScrollView></View>
}
function pace(sec:number){const m=Math.floor(sec/60),s=String(Math.round(sec%60)).padStart(2,'0');return `${m}'${s}\"/km`}
function Metric({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <View style={s.metric}>{icon}<Text style={s.metricVal}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:Colors.bg,gap:10},notFound:{fontWeight:FontWeight.bold,color:Colors.textPrimary},link:{color:Colors.electric,fontWeight:FontWeight.bold},header:{height:68,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:10,backgroundColor:'#fff',borderBottomWidth:1,borderColor:Colors.borderLight},back:{width:38,height:38,borderRadius:13,backgroundColor:Colors.bgAlt,alignItems:'center',justifyContent:'center'},name:{fontSize:14,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},liveLabel:{flexDirection:'row',gap:5,alignItems:'center',marginTop:2},dot:{width:6,height:6,borderRadius:3,backgroundColor:'#FB7185'},liveText:{fontSize:8.5,color:'#E11D48',fontWeight:FontWeight.extrabold,letterSpacing:.7},map:{height:310,margin:16,borderRadius:24,overflow:'hidden',...Shadow.md},mapBadge:{position:'absolute',left:12,bottom:12,backgroundColor:'rgba(8,18,38,.82)',borderRadius:99,paddingHorizontal:9,paddingVertical:7,flexDirection:'row',alignItems:'center',gap:5},mapBadgeText:{fontSize:9,color:'#fff',fontWeight:FontWeight.bold},metrics:{marginHorizontal:16,backgroundColor:'#fff',borderRadius:20,padding:13,flexDirection:'row',...Shadow.sm},metric:{flex:1,alignItems:'center',gap:4},metricVal:{fontSize:15,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},metricLabel:{fontSize:9.5,color:Colors.textTertiary},card:{marginHorizontal:16,marginTop:12,backgroundColor:'#fff',borderRadius:20,padding:15,...Shadow.sm},cardHead:{flexDirection:'row',alignItems:'center',gap:8},cardTitle:{fontSize:13,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},trackTitle:{fontSize:15,fontWeight:FontWeight.extrabold,color:Colors.textPrimary,marginTop:12},trackSub:{fontSize:10.5,color:Colors.textTertiary,marginTop:2},note:{flexDirection:'row',gap:9,marginTop:12},noteDot:{width:8,height:8,borderRadius:4,backgroundColor:'#7C3AED',marginTop:5},noteAt:{fontSize:9.5,color:Colors.textTertiary,fontWeight:FontWeight.bold},noteText:{fontSize:12,color:Colors.textPrimary,marginTop:2,lineHeight:17},empty:{fontSize:10.5,color:Colors.textTertiary,marginTop:7},reactions:{flexDirection:'row',gap:7,marginTop:12},reaction:{flex:1,backgroundColor:Colors.bg,borderRadius:13,paddingVertical:9,alignItems:'center'},emoji:{fontSize:18},count:{fontSize:9,color:Colors.textTertiary,fontWeight:FontWeight.bold,marginTop:2}})
