import React,{useCallback,useEffect,useMemo,useState}from'react'
import{View,Text,TextInput,StyleSheet,ScrollView,TouchableOpacity,Alert,ActivityIndicator,Share}from'react-native'
import{LinearGradient}from'expo-linear-gradient'
import{MapPin,Music2,MessageCircle,Share2,HeartPulse,Timer,Flame}from'lucide-react-native'
import{LiveRouteMap}from'@/components/live/LiveRouteMap'
import{router,useLocalSearchParams}from'expo-router'
import{Button}from'@/components/ui/Button'
import{Colors,FontSize,FontWeight,Radius,Spacing}from'@/constants/theme'
import{SPORTS_CONFIG}from'@/constants/sports'
import{supabase}from'@/lib/supabase'
import{useActivities}from'@/hooks/useActivities'
import{useSession}from'@/hooks/useProfile'
import{formatDurationLong}from'@/lib/units'
import type{Activity,SportType}from'@/types/database'

function toFrDate(iso:string){return new Date(iso).toLocaleDateString('fr-FR')}
function parseFrDate(value:string){const m=value.trim().match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(!m)return null;const d=new Date(+m[3],+m[2]-1,+m[1],12);return Number.isNaN(d.getTime())?null:d}

export default function ActivityDetail(){
 const{id}=useLocalSearchParams<{id:string}>();const{userId}=useSession();const{updateActivity,deleteActivity,addActivity}=useActivities(userId??undefined,3650)
 const[a,setA]=useState<Activity|null>(null),[loading,setLoading]=useState(true),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false)
 const[title,setTitle]=useState(''),[notes,setNotes]=useState(''),[date,setDate]=useState(''),[time,setTime]=useState('12:00'),[rpe,setRpe]=useState(''),[visibility,setVisibility]=useState<'public'|'followers'|'private'>('public')
 const load=useCallback(async()=>{if(!id)return;setLoading(true);const{data,error}=await supabase.from('activities').select('*').eq('id',id).maybeSingle();if(error)Alert.alert('Erreur',error.message);setA(data as any);if(data){const x=data as any;setTitle(x.title??'');setNotes(x.notes??'');setDate(toFrDate(x.performed_at??x.created_at));setTime(new Date(x.performed_at??x.created_at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}));setRpe(x.rpe?String(x.rpe):'');setVisibility(x.visibility??'public')}setLoading(false)},[id]);useEffect(()=>{load()},[load])
 const cfg=useMemo(()=>a?SPORTS_CONFIG[a.sport_type as SportType]:SPORTS_CONFIG.running,[a])
 const save=async()=>{if(!a)return;const d=parseFrDate(date);if(!d)return Alert.alert('Date invalide','Utilise JJ/MM/AAAA.');const tm=time.trim().match(/^(\d{1,2}):(\d{2})$/);if(!tm||+tm[1]>23||+tm[2]>59)return Alert.alert('Heure invalide','Utilise HH:MM.');d.setHours(+tm[1],+tm[2],0,0);const r=rpe?Number(rpe):null;if(r!==null&&(r<1||r>10))return Alert.alert('RPE invalide','Choisis une valeur entre 1 et 10.');setSaving(true);try{const next=await updateActivity(a.id,{title:title.trim()||null,notes:notes.trim()||null,performed_at:d.toISOString(),rpe:r,visibility});setA(next);setEditing(false)}catch(e:any){Alert.alert('Erreur',e.message)}finally{setSaving(false)}}
 const remove=()=>a&&Alert.alert('Supprimer cette activité ?','Cette action est irréversible.',[{text:'Annuler',style:'cancel'},{text:'Supprimer',style:'destructive',onPress:async()=>{try{await deleteActivity(a.id);router.back()}catch(e:any){Alert.alert('Erreur',e.message)}}}])
 const duplicate=async()=>{if(!a)return;try{const{ id:_id,created_at:_c,updated_at:_u,...copy}=a as any;await addActivity({...copy,title:a.title?`${a.title} (copie)`:null,performed_at:new Date().toISOString(),source:'manual',source_external_id:null,is_verified:false});Alert.alert('Activité dupliquée','La copie a été créée à la date d’aujourd’hui.')}catch(e:any){Alert.alert('Erreur',e.message)}}
 if(loading)return <View style={s.center}><ActivityIndicator color={Colors.electric}/></View>
 if(!a)return <View style={s.center}><Text>Activité introuvable.</Text></View>
 const shareStory=()=>Share.share({message:`${a.title||cfg.labelLong} · ${formatDurationLong(a.duration_seconds)}${a.metrics?.distance_km?` · ${Number(a.metrics.distance_km).toFixed(2)} km`:''} — Activity Story Hybrid.App`})
 return <View style={s.root}><View style={s.header}><TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>← Retour</Text></TouchableOpacity><View style={s.headerActions}>{!editing&&<TouchableOpacity onPress={shareStory} style={s.shareBtn}><Share2 size={15} color={Colors.electric}/><Text style={s.edit}>Partager</Text></TouchableOpacity>}<TouchableOpacity onPress={()=>setEditing(v=>!v)}><Text style={s.edit}>{editing?'Annuler':'Modifier'}</Text></TouchableOpacity></View></View><ScrollView contentContainerStyle={s.content}>
   <View style={[s.hero,{borderColor:cfg.color+'55'}]}><Text style={[s.sport,{color:cfg.color}]}>{cfg.labelLong}</Text><Text style={s.duration}>{formatDurationLong(a.duration_seconds)}</Text><Text style={s.source}>{a.is_verified?'✓ Activité vérifiée':`Source : ${a.source==='manual'?'saisie manuelle':a.source}`}</Text></View>
   {editing?<View style={s.card}><Label text="Titre"/><TextInput value={title} onChangeText={setTitle} style={s.input}/><Label text="Date (JJ/MM/AAAA)"/><TextInput value={date} onChangeText={setDate} style={s.input}/><Label text="Heure (HH:MM)"/><TextInput value={time} onChangeText={setTime} style={s.input}/><Label text="RPE (1–10)"/><TextInput value={rpe} onChangeText={setRpe} keyboardType="number-pad" style={s.input}/><Label text="Visibilité"/><View style={s.row}>{(['public','followers','private'] as const).map(v=><TouchableOpacity key={v} onPress={()=>setVisibility(v)} style={[s.chip,visibility===v&&s.active]}><Text style={[s.chipText,visibility===v&&s.activeText]}>{v==='public'?'Public':v==='followers'?'Abonnés':'Privé'}</Text></TouchableOpacity>)}</View><Label text="Notes"/><TextInput multiline value={notes} onChangeText={setNotes} style={[s.input,s.notes]}/><Button label="Enregistrer" loading={saving} onPress={save}/></View>:<>
   <LinearGradient colors={[cfg.color+'26','#FFFFFF']} style={s.storyHero}>
      <View style={s.storyMap}><LiveRouteMap progress={1}/></View>
      <View style={s.storyOverlay}><Text style={[s.storySport,{color:cfg.color}]}>{cfg.labelLong.toUpperCase()}</Text><Text style={s.storyTitle}>{a.title||'Activity Story'}</Text><Text style={s.storyDate}>{new Date(a.performed_at??a.created_at).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})}</Text></View>
    </LinearGradient>
    <View style={s.storyMetrics}><StoryMetric icon={<Timer size={17} color={cfg.color}/>} value={formatDurationLong(a.duration_seconds)} label="Durée"/><StoryMetric icon={<MapPin size={17} color='#06B6D4'/>} value={a.metrics?.distance_km?`${Number(a.metrics.distance_km).toFixed(2)} km`:'—'} label="Distance"/><StoryMetric icon={<HeartPulse size={17} color='#FB7185'/>} value={a.metrics?.heart_rate||a.metrics?.avg_heart_rate?`${a.metrics?.heart_rate??a.metrics?.avg_heart_rate} bpm`:'—'} label="FC"/><StoryMetric icon={<Flame size={17} color='#F59E0B'/>} value={a.calories_burned?`${a.calories_burned}`:'—'} label="kcal"/></View>
    <View style={s.memoryCard}><View style={s.memoryTop}><Music2 size={18} color='#22C55E'/><View style={{flex:1}}><Text style={s.memoryTitle}>Soundtrack de la séance</Text><Text style={s.memorySub}>{a.metrics?.current_track?.title?`${a.metrics.current_track.title} · ${a.metrics.current_track.artist??''}`:'Connecte Spotify pour garder la musique de tes efforts.'}</Text></View></View></View>
    {a.notes?<View style={s.memoryCard}><View style={s.memoryTop}><MessageCircle size={18} color='#7C3AED'/><View style={{flex:1}}><Text style={s.memoryTitle}>Journal de l’effort</Text><Text style={s.memorySub}>{a.notes}</Text></View></View></View>:null}
    <View style={s.card}><Metric label="Date" value={new Date(a.performed_at??a.created_at).toLocaleString('fr-FR')}/><Metric label="Calories" value={a.calories_burned?`${a.calories_burned} kcal`:'—'}/><Metric label="RPE" value={a.rpe?`${a.rpe}/10`:'—'}/><Metric label="Ressenti" value={a.mood?['😫','😕','😐','🙂','🔥'][a.mood-1]:'—'}/><Metric label="Visibilité" value={a.visibility??'public'}/></View>
   {a.title||a.notes?<View style={s.card}>{a.title?<Text style={s.title}>{a.title}</Text>:null}{a.notes?<Text style={s.body}>{a.notes}</Text>:null}</View>:null}
   <View style={s.card}><Text style={s.title}>Données sportives</Text>{Object.entries(a.metrics??{}).map(([k,v])=><Metric key={k} label={k.replace(/_/g,' ')} value={typeof v==='object'?JSON.stringify(v):String(v)}/>)}</View>
   <Button label="Dupliquer la séance" variant="ghost" onPress={duplicate}/><Button label="Supprimer la séance" variant="danger" onPress={remove}/>
   </>}
 </ScrollView></View>
}
function StoryMetric({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <View style={s.storyMetric}>{icon}<Text style={s.storyMetricValue}>{value}</Text><Text style={s.storyMetricLabel}>{label}</Text></View>}
function Label({text}:{text:string}){return <Text style={s.label}>{text}</Text>}function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:Colors.bg},header:{paddingTop:54,paddingHorizontal:Spacing.md,paddingBottom:10,flexDirection:'row',justifyContent:'space-between'},back:{color:Colors.electric,fontWeight:FontWeight.semibold},headerActions:{flexDirection:'row',gap:14,alignItems:'center'},shareBtn:{flexDirection:'row',gap:5,alignItems:'center'},edit:{color:Colors.electric,fontWeight:FontWeight.bold},content:{padding:Spacing.md,gap:Spacing.md,paddingBottom:50},hero:{backgroundColor:Colors.bgCard,borderRadius:Radius.xl,padding:Spacing.lg,borderWidth:1},sport:{fontSize:FontSize.xl,fontWeight:FontWeight.extrabold},duration:{fontSize:30,fontWeight:FontWeight.extrabold,color:Colors.textPrimary,marginTop:6},source:{fontSize:FontSize.xs,color:Colors.textTertiary,marginTop:4},card:{backgroundColor:Colors.bgCard,borderRadius:Radius.lg,padding:Spacing.md,gap:10},label:{fontSize:FontSize.xs,color:Colors.textSecondary,fontWeight:FontWeight.semibold},input:{height:46,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,paddingHorizontal:12,color:Colors.textPrimary,backgroundColor:Colors.bg},notes:{height:90,textAlignVertical:'top',paddingTop:12},row:{flexDirection:'row',gap:8},chip:{flex:1,paddingVertical:10,alignItems:'center',borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md},active:{borderColor:Colors.electric,backgroundColor:Colors.electricDim},chipText:{fontSize:12,color:Colors.textSecondary},activeText:{color:Colors.electric,fontWeight:FontWeight.bold},metric:{flexDirection:'row',gap:12},metricLabel:{flex:1,color:Colors.textSecondary,textTransform:'capitalize'},metricValue:{flex:1,color:Colors.textPrimary,fontWeight:FontWeight.semibold,textAlign:'right'},title:{fontSize:FontSize.md,fontWeight:FontWeight.bold,color:Colors.textPrimary},body:{color:Colors.textSecondary,lineHeight:20},storyHero:{borderRadius:Radius.xl,overflow:'hidden',minHeight:275},storyMap:{height:190,opacity:.96},storyOverlay:{padding:16},storySport:{fontSize:9,fontWeight:FontWeight.extrabold,letterSpacing:1.3},storyTitle:{fontSize:22,fontWeight:FontWeight.extrabold,color:Colors.textPrimary,marginTop:3},storyDate:{fontSize:10.5,color:Colors.textSecondary,marginTop:2,textTransform:'capitalize'},storyMetrics:{backgroundColor:'#fff',borderRadius:Radius.lg,padding:11,flexDirection:'row'},storyMetric:{flex:1,alignItems:'center',gap:4},storyMetricValue:{fontSize:13,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},storyMetricLabel:{fontSize:9,color:Colors.textTertiary},memoryCard:{backgroundColor:'#fff',borderRadius:Radius.lg,padding:14},memoryTop:{flexDirection:'row',gap:10,alignItems:'flex-start'},memoryTitle:{fontSize:12.5,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},memorySub:{fontSize:10.5,lineHeight:16,color:Colors.textSecondary,marginTop:3}})
