import React,{useMemo,useState}from'react'
import{View,Text,StyleSheet,TouchableOpacity}from'react-native'
import{LinearGradient}from'expo-linear-gradient'
import{Target,Flame,Shuffle,ShieldCheck,CheckCircle2}from'lucide-react-native'
import{Colors,FontWeight,Shadow,Spacing}from'@/constants/theme'
import type{Activity}from'@/types/database'
import{SPORT_BY_KEY}from'@/constants/sportCatalog'
import{useProgression}from'@/hooks/useProgression'
import{CLASS_BY_KEY}from'@/constants/v5'
import{RewardBurst}from'@/components/v5/RewardBurst'
export function HybridMissions({activities}:{activities:Activity[]}){const prog=useProgression();const cls=prog.athleteClass?CLASS_BY_KEY[prog.athleteClass]:undefined;const[reward,setReward]=useState<any>(null);const missions=useMemo(()=>{const now=Date.now();const week=activities.filter(a=>now-new Date(a.performed_at??a.created_at).getTime()<7*86400000);const days=new Set(week.map(a=>(a.performed_at??a.created_at).slice(0,10))).size;const fam=new Set(week.map(a=>SPORT_BY_KEY[a.sport_type]?.family).filter(Boolean)).size;const easy=week.filter(a=>(a.rpe??5)<=5).length;return[{key:'regularity',title:'Régulier, pas parfait',desc:'Bouge 4 jours différents cette semaine',value:Math.min(days,4),target:4,xp:120,color:'#F59E0B',Icon:Flame},{key:'hybrid',title:'Vraiment hybride',desc:'Pratique 3 familles de sports différentes',value:Math.min(fam,3),target:3,xp:180,color:'#8B5CF6',Icon:Shuffle},{key:'recovery',title:'Intelligent > épuisé',desc:'Enregistre une séance facile / récupération',value:Math.min(easy,1),target:1,xp:80,color:'#10B981',Icon:ShieldCheck}]},[activities]);const claim=(m:any)=>{if(m.value<m.target||prog.claimed.includes(`week:${m.key}`))return;const mult=cls?.key==='hybrid'?1.07:1;const xp=Math.round(m.xp*mult);prog.addXp(xp,`week:${m.key}`);setReward({...m,xp})};return <View style={s.wrap}><View style={s.head}><View><Text style={s.eyebrow}>MISSIONS HYBRID</Text><Text style={s.title}>Niveau {prog.level} · {prog.xp} XP</Text></View><View style={s.xp}><Target size={15} color="#7C3AED"/><Text style={s.xpText}>{Math.round(prog.progress*100)}% vers niv. {prog.level+1}</Text></View></View>{missions.map(m=>{const pct=Math.min(1,m.value/m.target),done=m.value>=m.target,claimed=prog.claimed.includes(`week:${m.key}`);return <TouchableOpacity key={m.key} style={[s.card,done&&!claimed&&{borderWidth:1.5,borderColor:m.color+'55'}]} activeOpacity={.9} onPress={()=>claim(m)}><View style={[s.icon,{backgroundColor:m.color+'17'}]}>{claimed?<CheckCircle2 size={19} color={m.color}/>:<m.Icon size={18} color={m.color}/>}</View><View style={{flex:1}}><View style={s.cardTop}><Text style={s.cardTitle}>{m.title}</Text><Text style={[s.reward,{color:m.color}]}>{claimed?'RÉCUPÉRÉ':done?`RÉCUPÉRER +${m.xp} XP`:`+${m.xp} XP`}</Text></View><Text style={s.desc}>{m.desc}</Text><View style={s.progress}><View style={[s.fill,{width:`${Math.max(3,pct*100)}%`,backgroundColor:m.color}]}/></View><Text style={s.value}>{m.value}/{m.target}</Text></View></TouchableOpacity>})}<LinearGradient colors={['#F5F3FF','#EEF2FF']} style={s.footer}><Text style={s.footerTitle}>{cls?`Classe ${cls.name} · ${cls.boostLabel}`:'Choisis une classe pour spécialiser ta progression.'}</Text><Text style={s.footerSub}>Les XP débloquent niveaux, badges et cosmétiques. Les performances officielles restent inchangées.</Text></LinearGradient><RewardBurst visible={!!reward} title="Mission accomplie" subtitle={reward?.title} xp={reward?.xp??0} onClose={()=>setReward(null)}/></View>}
const s=StyleSheet.create({wrap:{paddingHorizontal:Spacing.md,gap:8,marginBottom:Spacing.md},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:2},eyebrow:{fontSize:8.5,color:'#7C3AED',fontWeight:FontWeight.extrabold,letterSpacing:1.1},title:{fontSize:15,fontWeight:FontWeight.extrabold,color:Colors.textPrimary,marginTop:2},xp:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:'#F5F3FF',paddingHorizontal:9,paddingVertical:6,borderRadius:99},xpText:{fontSize:8.5,color:'#7C3AED',fontWeight:FontWeight.extrabold},card:{backgroundColor:'#fff',borderRadius:17,padding:11,flexDirection:'row',alignItems:'center',gap:9,...Shadow.sm},icon:{width:38,height:38,borderRadius:12,alignItems:'center',justifyContent:'center'},cardTop:{flexDirection:'row',justifyContent:'space-between',gap:8},cardTitle:{fontSize:11.5,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},reward:{fontSize:8.5,fontWeight:FontWeight.extrabold},desc:{fontSize:9.5,color:Colors.textTertiary,marginTop:2},progress:{height:5,backgroundColor:Colors.bgAlt,borderRadius:99,overflow:'hidden',marginTop:7,marginRight:28},fill:{height:'100%',borderRadius:99},value:{position:'absolute',right:0,bottom:0,fontSize:8.5,color:Colors.textTertiary,fontWeight:FontWeight.bold},footer:{borderRadius:15,padding:11,marginTop:1},footerTitle:{fontSize:10,fontWeight:FontWeight.extrabold,color:'#5B21B6'},footerSub:{fontSize:9,color:'#6D28D9',lineHeight:13,marginTop:2}})
