import React from 'react'
import { View, Text, StyleSheet } from 'react-native'
import Svg, { Polygon, Line, Circle } from 'react-native-svg'
import Animated,{FadeIn,FadeInUp}from'react-native-reanimated'
import { Colors, FontSize, FontWeight, Radius, Shadow, SkillColors, Spacing } from '@/constants/theme'
import type { SkillScores } from '@/hooks/useSkills'
import {useSensoryPreferences}from'@/hooks/useSensoryPreferences'
const KEYS:[keyof SkillScores,string,string][]=[['endurance','Endurance',SkillColors.endurance],['strength','Force',SkillColors.strength],['speed','Vitesse',SkillColors.speed],['consistency','Régularité',SkillColors.consistency],['versatility','Polyvalence',SkillColors.versatility],['progression','Progression',SkillColors.progression]]
const SIZE=250,C=125,R=86
const point=(i:number,r:number)=>{const a=-Math.PI/2+i*(Math.PI*2/6);return[C+Math.cos(a)*r,C+Math.sin(a)*r]}
const pts=(r:number)=>KEYS.map((_,i)=>point(i,r).join(',')).join(' ')
export function SkillsRadar({skills}:{skills:SkillScores}){const{prefs}=useSensoryPreferences();const data=KEYS.map(([k],i)=>point(i,R*Math.max(0,Math.min(100,Number(skills[k])))/100).join(',')).join(' ');return <Animated.View entering={prefs.reducedMotion?undefined:FadeInUp.duration(430).springify().damping(18)} style={s.card}><View style={s.head}><View><Text style={s.eyebrow}>PROFIL ATHLÉTIQUE</Text><Text style={s.title}>Compétences hybrides</Text></View><View style={s.overall}><Text style={s.score}>{skills.overall}</Text><Text style={s.outof}>/100</Text></View></View><View style={s.chartWrap}><Svg width={SIZE} height={SIZE}>{[.25,.5,.75,1].map(x=><Polygon key={x} points={pts(R*x)} fill={x===1?'rgba(49,92,255,.025)':'transparent'} stroke={x===1?'#CFDAE9':'#E6EDF5'} strokeWidth={1}/>)}{KEYS.map((_,i)=>{const[x,y]=point(i,R);return <Line key={i} x1={C} y1={C} x2={x} y2={y} stroke="#E6EDF5" strokeWidth={1}/>})}<Polygon points={data} fill="rgba(49,92,255,.16)" stroke="#315CFF" strokeWidth={2.5}/>{KEYS.map(([k,,color],i)=>{const[x,y]=point(i,R*Math.max(0,Math.min(100,Number(skills[k])))/100);return <Circle key={String(k)} cx={x} cy={y} r={4.4} fill={color} stroke="#fff" strokeWidth={2}/>})}</Svg>{KEYS.map(([k,label,color],i)=>{const[x,y]=point(i,R+27);return <View key={String(k)} style={[s.radarLabel,{left:x-42,top:y-18}]}><Text numberOfLines={1} style={[s.radarLabelText,{color}]}>{label}</Text><Text style={s.radarValue}>{skills[k]}</Text></View>})}</View><View style={s.legend}>{KEYS.map(([k,label,color],i)=><Animated.View entering={prefs.reducedMotion?undefined:FadeIn.delay(80+i*40).duration(260)} key={String(k)} style={s.legendItem}><View style={[s.dot,{backgroundColor:color}]}/><Text style={s.legendLabel}>{label}</Text><Text style={[s.legendValue,{color}]}>{skills[k]}</Text></Animated.View>)}</View></Animated.View>}
const s=StyleSheet.create({card:{backgroundColor:Colors.bgCard,borderRadius:Radius.xl,padding:Spacing.md,...Shadow.md,borderWidth:1,borderColor:Colors.borderLight},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},eyebrow:{fontSize:9,color:Colors.electric,fontWeight:FontWeight.extrabold,letterSpacing:1.6},title:{fontSize:FontSize.lg,fontWeight:FontWeight.extrabold,color:Colors.textPrimary,marginTop:2},overall:{flexDirection:'row',alignItems:'baseline',backgroundColor:Colors.electricDim,paddingHorizontal:11,paddingVertical:7,borderRadius:Radius.md},score:{fontSize:22,fontWeight:FontWeight.extrabold,color:Colors.electric},outof:{fontSize:10,fontWeight:FontWeight.bold,color:Colors.textTertiary},chartWrap:{width:SIZE,height:SIZE,alignSelf:'center',position:'relative',marginTop:2},radarLabel:{position:'absolute',width:84,alignItems:'center'},radarLabelText:{fontSize:9,fontWeight:FontWeight.bold},radarValue:{fontSize:9,color:Colors.textTertiary,fontWeight:FontWeight.bold},legend:{flexDirection:'row',flexWrap:'wrap',borderTopWidth:1,borderTopColor:Colors.borderLight,paddingTop:12,rowGap:9},legendItem:{width:'50%',flexDirection:'row',alignItems:'center',paddingRight:8},dot:{width:8,height:8,borderRadius:4,marginRight:6},legendLabel:{flex:1,fontSize:11,color:Colors.textSecondary},legendValue:{fontSize:11,fontWeight:FontWeight.extrabold}})
