import type{Activity,SportType}from'@/types/database'
import{SPORT_BY_KEY}from'@/constants/sportCatalog'
export type CoachPlan={sport:SportType;title:string;duration:string;objective:string;why:string;blocks:string[];intensity:'Facile'|'Modérée'|'Soutenue'}
const templates:Record<string,(sport:SportType)=>Omit<CoachPlan,'sport'|'why'>>={
 badminton:()=>({title:'Footwork + explosivité badminton',duration:'45 min',objective:'Être plus rapide sur le premier pas et revenir au centre',intensity:'Soutenue',blocks:['8 min échauffement : corde légère + mobilité chevilles/hanches','4 × 45 s shadow badminton sur 6 coins · 45 s repos','6 × 20 s déplacements explosifs avant/arrière · 40 s repos','3 × 10 fentes latérales par côté + 3 × 8 sauts latéraux','8 min technique : services courts/longs ou gestes à vide','5 min retour au calme']}),
 swimming:()=>({title:'Technique + endurance natation',duration:'50 min',objective:'Améliorer l’efficacité sans perdre l’allure',intensity:'Modérée',blocks:['300 m facile','6 × 50 m éducatifs · 20 s repos','6 × 100 m à allure régulière · 20–30 s repos','4 × 25 m rapides · 30 s repos','200 m récupération']}),
 running:()=>({title:'Endurance + accélérations',duration:'45 min',objective:'Construire l’endurance tout en gardant de la vitesse',intensity:'Modérée',blocks:['12 min footing facile','25 min endurance conversationnelle','6 × 20 s vite / 60 s très facile','5 min retour au calme']}),
 trail_running:()=>({title:'Côtes trail',duration:'55 min',objective:'Force des jambes et relances en montée',intensity:'Soutenue',blocks:['15 min facile','8 × 45 s côte soutenue · redescente lente','20 min terrain vallonné facile','5 min mobilité chevilles/mollets']}),
 gym:()=>({title:'Full body hybride',duration:'60 min',objective:'Développer la force sans négliger le conditionnement',intensity:'Soutenue',blocks:['8 min échauffement + séries progressives','Squat 4 × 6 · RIR 2','Développé couché 4 × 6 · RIR 2','Rowing 4 × 8','Soulevé de terre roumain 3 × 8','Finisher 6 min : 30 s travail / 30 s repos']}),
 crossfit:()=>({title:'Force + Metcon court',duration:'50 min',objective:'Puissance et capacité à répéter les efforts',intensity:'Soutenue',blocks:['10 min mobilité + technique','Force : 5 × 3 mouvement principal à charge contrôlée','Metcon 12 min : alternance poussée / tirage / cardio','8 min récupération active']}),
 tennis:()=>({title:'Déplacements + régularité tennis',duration:'55 min',objective:'Arriver équilibré sur la balle et tenir l’échange',intensity:'Modérée',blocks:['10 min échauffement dynamique','4 × 2 min pas chassés + split-step','15 min diagonales régulières','10 min service + première balle','6 × 30 s points intenses · 60 s récupération']}),
 padel:()=>({title:'Volée + déplacements padel',duration:'50 min',objective:'Mieux contrôler le filet et les transitions',intensity:'Modérée',blocks:['8 min mobilité + petits pas','5 × 90 s shadow : fond → filet → replacement','15 min volées contrôlées','10 min sorties de vitre / gestes techniques','8 min jeu de jambes + gainage anti-rotation']}),
 table_tennis:()=>({title:'Réactivité ping-pong',duration:'40 min',objective:'Premier démarrage et qualité de placement',intensity:'Modérée',blocks:['5 min mobilité poignets/épaules','8 min services ciblés','4 × 4 min régularité coup droit/revers','6 × 45 s déplacements 2 points · 45 s repos','5 min retours de service']}),
 football:()=>({title:'Accélérations + appuis football',duration:'50 min',objective:'Répéter les efforts courts sans perdre en qualité',intensity:'Soutenue',blocks:['10 min conduite de balle + mobilité','2 × 6 accélérations 15–20 m · retour marché','4 × 2 min changements de direction avec ballon','3 × 8 fentes + 3 × 8 sauts','10 min technique ou frappes']}),
 basketball:()=>({title:'Appuis + détente basket',duration:'50 min',objective:'Premier pas, changements de direction et finition',intensity:'Soutenue',blocks:['8 min dribble + mobilité','5 × 45 s appuis défensifs · 45 s repos','4 × 5 sauts verticaux qualitatifs','12 min finitions main droite/gauche','10 min tirs après déplacement']}),
 climbing:()=>({title:'Technique + grip escalade',duration:'60 min',objective:'Être plus efficace avant de fatiguer les avant-bras',intensity:'Modérée',blocks:['10 min mobilité doigts/épaules + voies faciles','20 min technique : pieds silencieux et bras tendus','4 blocs/voies à difficulté contrôlée avec repos complet','3 × 30 s gainage + tirage scapulaire','10 min retour au calme, sans étirements agressifs des doigts']}),
 boxing:()=>({title:'Jeu de jambes + combinaisons boxe',duration:'45 min',objective:'Rester mobile et propre sous fatigue',intensity:'Soutenue',blocks:['8 min corde + mobilité','4 × 2 min shadow : déplacements uniquement','4 × 2 min combinaisons 1–2 + sortie d’angle','3 × 2 min sac/pattes à intensité contrôlée','5 min retour au calme']}),
}
function familyPlan(sport:SportType):Omit<CoachPlan,'sport'|'why'>{const d=SPORT_BY_KEY[sport];switch(d?.family){case'racket':return templates.tennis(sport);case'aquatic':return templates.swimming(sport);case'running_endurance':case'cycling':case'paddle_boat':return templates.running(sport);case'strength_fitness':return templates.gym(sport);case'combat':return templates.boxing(sport);case'climbing_mountain':return templates.climbing(sport);case'team_ball':return templates.football(sport);case'mind_body':return{title:'Mobilité + contrôle',duration:'35 min',objective:'Améliorer l’amplitude utile et le contrôle',intensity:'Facile',blocks:['5 min respiration et mobilisation douce','15 min mobilité active des zones raides','10 min contrôle/gainage lent','5 min retour au calme']};default:return{title:`Séance ${d?.label??sport}`,duration:'45 min',objective:'Technique et condition physique spécifique',intensity:'Modérée',blocks:['10 min échauffement spécifique','20 min travail technique','10 min effort physique spécifique','5 min retour au calme']}}}
export function buildCoachPlans(sports:SportType[],activities:Activity[]):CoachPlan[]{const now=Date.now();return sports.slice(0,8).map(sport=>{const base=(templates[sport]??familyPlan)(sport);const last=activities.filter(a=>a.sport_type===sport).sort((a,b)=>new Date(b.performed_at).getTime()-new Date(a.performed_at).getTime())[0];const days=last?Math.floor((now-new Date(last.performed_at).getTime())/86400000):null;const hardRecent=activities.some(a=>a.sport_type===sport&&(a.rpe??0)>=9&&now-new Date(a.performed_at).getTime()<48*3600000);const why=hardRecent?'Ta dernière séance de ce sport était très intense : garde cette proposition contrôlée ou reporte-la si tu récupères mal.':days==null?'Tu n’as pas encore de séance enregistrée dans ce sport : voici une première base simple à personnaliser.':days>=7?`Ta dernière séance de ${SPORT_BY_KEY[sport]?.label??sport} remonte à ${days} jours : cette séance aide à reprendre le rythme.`:`Cette proposition complète ce que tu as enregistré récemment en ${SPORT_BY_KEY[sport]?.label??sport}.`;return{sport,...base,why}})}
