import React from 'react'
import { Tabs } from 'expo-router'
import { View, Text, StyleSheet, Platform } from 'react-native'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import { LinearGradient } from 'expo-linear-gradient'
import { StatusBar } from 'expo-status-bar'
import { Home, Trophy, User2, Dumbbell, BrainCircuit } from 'lucide-react-native'
import Animated,{FadeIn}from'react-native-reanimated'
import { Colors, FontWeight, Gradients, Shadow } from '@/constants/theme'
import { SensoryPressable } from '@/components/v6/SensoryPressable'

interface TabBarProps {state:{routes:{key:string;name:string}[];index:number};descriptors:Record<string,{options:Record<string,unknown>}>;navigation:{emit:(e:any)=>any;navigate:(name:string)=>void}}
const TABS=[{name:'index',label:'Today',Icon:Home},{name:'train',label:'Train',Icon:Dumbbell},{name:'coach',label:'Coach',Icon:BrainCircuit,center:true},{name:'arena',label:'Arène',Icon:Trophy},{name:'vous',label:'You',Icon:User2}]

function CustomTabBar({state,navigation}:TabBarProps){const insets=useSafeAreaInsets();return <View style={[bar.shell,{paddingBottom:Math.max(insets.bottom,9)}]}><View style={bar.container}>{state.routes.map((route,index)=>{const tab=TABS.find(t=>t.name===route.name);if(!tab)return null;const focused=state.index===index;const Icon=tab.Icon;const onPress=()=>{const e=navigation.emit({type:'tabPress',target:route.key,canPreventDefault:true});if(!focused&&!e.defaultPrevented)navigation.navigate(route.name)};if(tab.center)return <View key={route.key} style={bar.centerWrap}><SensoryPressable onPress={onPress} event="selection" scale={.94} style={bar.centerTouchable}><LinearGradient colors={focused?['#315CFF','#8B5CF6']:Gradients.pro} style={[bar.centerBtn,focused&&bar.centerBtnFocused]}>{focused&&<Animated.View entering={FadeIn.duration(180)} style={bar.centerGlow}/>}<Icon size={25} color="#fff" strokeWidth={2.6}/></LinearGradient></SensoryPressable><Text style={[bar.centerLabel,focused&&bar.centerLabelFocused]}>{tab.label}</Text></View>;return <SensoryPressable key={route.key} onPress={onPress} event="selection" style={bar.item} scale={.94}><View style={[bar.iconWrap,focused&&bar.iconWrapFocused]}>{focused&&<Animated.View entering={FadeIn.duration(180)} style={bar.activePill}/>}<Icon size={21} color={focused?Colors.electric:Colors.textTertiary} strokeWidth={focused?2.6:1.9}/></View><Text style={[bar.label,focused&&bar.labelFocused]}>{tab.label}</Text></SensoryPressable>})}</View></View>}
export default function TabLayout(){return <><StatusBar style="dark"/><Tabs tabBar={props=><CustomTabBar {...(props as any)}/>} screenOptions={{headerShown:false,animation:'fade'}}>{TABS.map(t=><Tabs.Screen key={t.name} name={t.name}/>)}</Tabs></>}
const bar=StyleSheet.create({shell:{backgroundColor:'transparent',paddingHorizontal:8,paddingTop:5},container:{flexDirection:'row',backgroundColor:'rgba(255,255,255,.98)',borderWidth:1,borderColor:Colors.borderLight,borderRadius:24,height:68,alignItems:'flex-end',paddingHorizontal:4,...Shadow.lg,...Platform.select({ios:{shadowOpacity:.11},android:{elevation:18}})},item:{flex:1,alignItems:'center',justifyContent:'center',paddingBottom:7,gap:2,height:62},iconWrap:{width:43,height:34,borderRadius:13,alignItems:'center',justifyContent:'center',position:'relative',overflow:'hidden'},iconWrapFocused:{backgroundColor:'rgba(49,92,255,.07)'},activePill:{position:'absolute',left:6,right:6,top:4,bottom:4,borderRadius:10,backgroundColor:'rgba(49,92,255,.06)'},label:{fontSize:9.5,color:Colors.textTertiary,fontWeight:FontWeight.semibold,letterSpacing:.15},labelFocused:{color:Colors.electric,fontWeight:FontWeight.extrabold},centerWrap:{flex:1,alignItems:'center',justifyContent:'flex-end',paddingBottom:7,gap:2},centerTouchable:{marginTop:-22},centerBtn:{width:58,height:58,borderRadius:20,alignItems:'center',justifyContent:'center',overflow:'hidden',shadowColor:Colors.electric,shadowOffset:{width:0,height:7},shadowOpacity:.4,shadowRadius:16,elevation:12},centerBtnFocused:{transform:[{translateY:-2}]},centerGlow:{position:'absolute',width:34,height:34,borderRadius:17,backgroundColor:'rgba(255,255,255,.12)'},centerLabel:{fontSize:9.5,color:Colors.textTertiary,fontWeight:FontWeight.semibold},centerLabelFocused:{color:Colors.electric,fontWeight:FontWeight.extrabold}})
