import React from 'react'
import { View, Text, StyleSheet, ScrollView } from 'react-native'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import { router } from 'expo-router'
import { LinearGradient } from 'expo-linear-gradient'
import { Play, CalendarDays, WandSparkles, Route, Dumbbell, Waves, Activity, ChevronRight } from 'lucide-react-native'
import { Colors, FontWeight, Radius, Shadow, Spacing } from '@/constants/theme'
import { useSession, useProfile } from '@/hooks/useProfile'
import { useActivities } from '@/hooks/useActivities'
import { useLifeCheckin } from '@/hooks/useLifeCheckin'
import { useAdaptiveOS } from '@/hooks/v12/useAdaptiveOS'
import { PHASE_META } from '@/constants/v12'
import { SensoryPressable } from '@/components/v6/SensoryPressable'
import { SPORT_BY_KEY } from '@/constants/sportCatalog'

export default function TrainScreen(){
 const inset=useSafeAreaInsets();const{userId}=useSession();const{profile}=useProfile(userId??undefined);const{activities}=useActivities(userId??undefined,3650);const{checkin}=useLifeCheckin(userId??undefined);const{snapshot,preferences}=useAdaptiveOS(activities,profile?.favorite_sports??[],checkin);const meta=PHASE_META[snapshot.phase]
 return <ScrollView style={s.root} contentContainerStyle={[s.wrap,{paddingTop:inset.top+12}]} showsVerticalScrollIndicator={false}>
   <Text style={s.eyebrow}>TRAIN</Text><Text style={s.h1}>Entraîne-toi avec un plan qui s’adapte.</Text><Text style={s.lead}>Tracker, planning, séances structurées et adaptation selon ta forme réelle.</Text>
   <LinearGradient colors={['#172554','#243B80','#315CFF']} style={s.hero}><View style={s.heroTop}><View><Text style={s.heroLabel}>PHASE ACTUELLE</Text><Text style={s.heroTitle}>{meta.label}</Text></View><View style={[s.phase,{backgroundColor:meta.color+'22',borderColor:meta.color}]}><Text style={[s.phaseText,{color:meta.color}]}>{preferences.mode.toUpperCase()}</Text></View></View><Text style={s.heroSub}>{snapshot.headline}</Text><Text style={s.heroNext}>{snapshot.nextBestAction}</Text><SensoryPressable onPress={()=>router.push('/modals/track' as any)} event="success" style={s.start}><Play size={18} color="#111827" fill="#111827"/><Text style={s.startText}>Démarrer une séance</Text></SensoryPressable></LinearGradient>
   <View style={s.grid}><Quick icon={CalendarDays} label="Plan adaptatif" sub="Ta semaine" onPress={()=>router.push('/modals/adaptive-plan' as any)}/><Quick icon={WandSparkles} label="Générer" sub="Selon ton temps" onPress={()=>router.push('/modals/adaptive-plan' as any)}/><Quick icon={Route} label="Tracker GPS" sub="Course, vélo, trail" onPress={()=>router.push('/modals/track' as any)}/><Quick icon={Activity} label="Scénarios" sub="Et si… ?" onPress={()=>router.push('/modals/scenario-lab' as any)}/></View>
   <View style={s.sectionHead}><Text style={s.section}>Cette semaine</Text><Text style={s.muted}>{snapshot.planConfidence}% confiance</Text></View>
   {snapshot.plan.map((item,i)=>{const sp=SPORT_BY_KEY[item.sport];return <SensoryPressable key={item.id} onPress={()=>router.push('/modals/adaptive-plan' as any)} style={s.session} event="selection"><View style={[s.day,{backgroundColor:(sp?.color??Colors.electric)+'14'}]}><Text style={[s.dayText,{color:sp?.color??Colors.electric}]}>{new Date(item.date+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'short'}).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.sessionTitle}>{item.title}</Text><Text style={s.sessionMeta}>{item.durationMinutes} min · {item.intensity} · {item.status==='adapted'?'adaptée':'prévue'}</Text></View><ChevronRight size={17} color={Colors.textTertiary}/></SensoryPressable>})}
   <Text style={s.section}>Outils de séance</Text><View style={s.tools}><Tool icon={Dumbbell} title="Musculation" text="Séries, repos, RIR, PR, volume"/><Tool icon={Waves} title="Natation" text="Longueurs, séries, allure /100 m"/><Tool icon={Route} title="Endurance" text="GPS, laps, Ghost, Pacer"/></View>
 </ScrollView>
}
function Quick({icon:Icon,label,sub,onPress}:{icon:any;label:string;sub:string;onPress:()=>void}){return <SensoryPressable onPress={onPress} style={s.quick} event="selection"><View style={s.quickIcon}><Icon size={19} color={Colors.electric}/></View><Text style={s.quickTitle}>{label}</Text><Text style={s.quickSub}>{sub}</Text></SensoryPressable>}
function Tool({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <View style={s.tool}><Icon size={18} color={Colors.violet}/><View><Text style={s.toolTitle}>{title}</Text><Text style={s.toolText}>{text}</Text></View></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},wrap:{padding:Spacing.md,paddingBottom:110,gap:12},eyebrow:{fontSize:9,color:Colors.electric,fontWeight:FontWeight.extrabold,letterSpacing:1.5},h1:{fontSize:27,color:Colors.textPrimary,fontWeight:FontWeight.extrabold,lineHeight:31},lead:{fontSize:12,color:Colors.textSecondary,lineHeight:18},hero:{borderRadius:27,padding:17,gap:11,...Shadow.lg},heroTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},heroLabel:{fontSize:8,color:'#A5B4FC',fontWeight:FontWeight.extrabold,letterSpacing:1.1},heroTitle:{fontSize:24,color:'#fff',fontWeight:FontWeight.extrabold,marginTop:2},heroSub:{fontSize:12,color:'#DDE5FF'},heroNext:{fontSize:11,color:'#fff',fontWeight:FontWeight.bold,backgroundColor:'rgba(255,255,255,.09)',borderRadius:13,padding:10},phase:{borderWidth:1,borderRadius:99,paddingHorizontal:8,paddingVertical:5},phaseText:{fontSize:8,fontWeight:FontWeight.extrabold},start:{height:46,borderRadius:15,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},startText:{color:'#111827',fontWeight:FontWeight.extrabold,fontSize:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:9},quick:{width:'48.5%',backgroundColor:'#fff',borderRadius:18,padding:12,...Shadow.sm},quickIcon:{width:34,height:34,borderRadius:11,backgroundColor:Colors.electricDim,alignItems:'center',justifyContent:'center',marginBottom:8},quickTitle:{fontSize:12,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},quickSub:{fontSize:9.5,color:Colors.textTertiary,marginTop:2},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:5},section:{fontSize:15,fontWeight:FontWeight.extrabold,color:Colors.textPrimary,marginTop:5},muted:{fontSize:9.5,color:Colors.textTertiary},session:{backgroundColor:'#fff',borderRadius:17,padding:10,flexDirection:'row',alignItems:'center',gap:10,...Shadow.sm},day:{width:44,height:44,borderRadius:13,alignItems:'center',justifyContent:'center'},dayText:{fontSize:9,fontWeight:FontWeight.extrabold},sessionTitle:{fontSize:11.5,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},sessionMeta:{fontSize:9.5,color:Colors.textTertiary,marginTop:3},tools:{gap:8},tool:{backgroundColor:'#fff',borderRadius:16,padding:12,flexDirection:'row',gap:10,alignItems:'center'},toolTitle:{fontSize:11.5,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},toolText:{fontSize:9.5,color:Colors.textTertiary,marginTop:2}})
