import React,{useState}from'react'
import{View,Text,TextInput,StyleSheet,ScrollView,Alert,Share,TouchableOpacity}from'react-native'
import{router}from'expo-router'
import{supabase}from'@/lib/supabase'
import{Button}from'@/components/ui/Button'
import{Colors,FontSize,FontWeight,Radius,Spacing}from'@/constants/theme'
import{useSession}from'@/hooks/useProfile'
export default function AccountModal(){const{userId,email}=useSession();const[newEmail,setNewEmail]=useState(email??''),[password,setPassword]=useState('');const changeEmail=async()=>{if(!newEmail.trim())return;const{error}=await supabase.auth.updateUser({email:newEmail.trim().toLowerCase()});Alert.alert(error?'Erreur':'Email',''+(error?.message??'Un email de confirmation peut être envoyé selon la configuration Supabase.'))};const changePassword=async()=>{if(password.length<8)return Alert.alert('Mot de passe','8 caractères minimum.');const{error}=await supabase.auth.updateUser({password});Alert.alert(error?'Erreur':'Mot de passe',error?.message??'Mot de passe modifié.');if(!error)setPassword('')};const exportData=async()=>{if(!userId)return;const[{data:profile},{data:activities},{data:posts}]=await Promise.all([supabase.rpc('get_my_profile'),supabase.from('activities').select('*').eq('user_id',userId),supabase.from('posts').select('*').eq('user_id',userId)]);await Share.share({message:JSON.stringify({exported_at:new Date().toISOString(),profile,activities,posts},null,2),title:'Export Hybrid.App'})};const remove=()=>Alert.alert('Supprimer définitivement le compte ?','Cette action supprime le compte et les données liées. Elle est irréversible.',[{text:'Annuler',style:'cancel'},{text:'Supprimer',style:'destructive',onPress:async()=>{const{error}=await supabase.rpc('delete_my_account');if(error)return Alert.alert('Erreur',error.message);await supabase.auth.signOut();router.replace('/(auth)/login')}}]);return <View style={s.root}><View style={s.head}><TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>← Retour</Text></TouchableOpacity><Text style={s.title}>Compte</Text></View><ScrollView contentContainerStyle={s.content}><Section title="Adresse email"><TextInput value={newEmail} onChangeText={setNewEmail} autoCapitalize="none" keyboardType="email-address" style={s.input}/><Button label="Modifier l’email" onPress={changeEmail}/></Section><Section title="Mot de passe"><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Nouveau mot de passe" style={s.input}/><Button label="Modifier le mot de passe" onPress={changePassword}/></Section><Section title="Tes données"><Text style={s.desc}>Génère un export JSON de ton profil, tes activités et tes posts via la feuille de partage du téléphone.</Text><Button label="Exporter mes données" variant="ghost" onPress={exportData}/></Section><Section title="Informations"><Text style={s.desc}>Politique de confidentialité et conditions d’utilisation : ajoute ici tes textes juridiques finaux avant publication.</Text></Section><Section title="Zone sensible"><Button label="Supprimer mon compte" variant="danger" onPress={remove}/></Section></ScrollView></View>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},head:{paddingTop:54,paddingHorizontal:Spacing.md,paddingBottom:12},back:{color:Colors.electric,fontWeight:FontWeight.semibold,marginBottom:10},title:{fontSize:FontSize.xl,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},content:{padding:Spacing.md,gap:Spacing.md,paddingBottom:50},section:{backgroundColor:Colors.bgCard,borderRadius:Radius.lg,padding:Spacing.md,gap:10},sectionTitle:{fontSize:FontSize.md,fontWeight:FontWeight.bold,color:Colors.textPrimary},desc:{color:Colors.textSecondary,lineHeight:20},input:{height:48,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,paddingHorizontal:12,color:Colors.textPrimary,backgroundColor:Colors.bg}})
