import React,{useEffect,useState}from'react'
import{Image,ScrollView,StyleSheet,Text,View}from'react-native'
import{router}from'expo-router'
import{BrainCircuit,Camera,CheckCircle2,ChevronLeft,ImagePlus,LockKeyhole,Sparkles,Trash2}from'lucide-react-native'
import AsyncStorage from'@react-native-async-storage/async-storage'
import * as ImagePicker from'expo-image-picker'
import{HybridAvatar2D}from'@/components/v14/HybridAvatar2D'
import{SensoryPressable}from'@/components/v6/SensoryPressable'
import{useV7Economy}from'@/hooks/v7/useV7Economy'
import{useV14Identity}from'@/hooks/v14/useV14Identity'
import{analyzeAvatarSelfie}from'@/lib/v14/avatarFaceAssist'
import{Colors,FontWeight,Shadow}from'@/constants/theme'
const KEY='hybrid:v14:selfie-reference'
export default function AvatarPhoto(){
 const{state,equip}=useV7Economy();const{state:identity,update}=useV14Identity();const[uri,setUri]=useState<string>();const[busy,setBusy]=useState(false);const[message,setMessage]=useState('')
 useEffect(()=>{AsyncStorage.getItem(KEY).then(v=>{if(v)setUri(v)}).catch(()=>{})},[])
 const saveUri=(u:string)=>{setUri(u);AsyncStorage.setItem(KEY,u).catch(()=>{});update({photoAssistLast:new Date().toISOString(),photoAssistStatus:'ready'})}
 const pick=async(camera=false)=>{if(camera){const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted){setMessage('Autorise la caméra pour prendre un selfie.');return}const r=await ImagePicker.launchCameraAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.82});if(!r.canceled&&r.assets[0]?.uri)saveUri(r.assets[0].uri)}else{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.82});if(!r.canceled&&r.assets[0]?.uri)saveUri(r.assets[0].uri)}}
 const analyze=async()=>{if(!uri)return;setBusy(true);setMessage('');const out=await analyzeAvatarSelfie(uri);setBusy(false);if(!out.ok){setMessage(out.message);update({photoAssistStatus:out.reason==='not_configured'?'needs_backend':'ready'});return}Object.values(out.result.suggested).forEach(id=>{if(id)equip(id)});update({photoAssistStatus:'applied'});setMessage(`${out.result.summary} · Confiance ${Math.round(out.result.confidence*100)} %`)}
 return <View style={s.root}><View style={s.top}><SensoryPressable event="selection" onPress={()=>router.back()} style={s.back}><ChevronLeft size={21} color={Colors.textPrimary}/></SensoryPressable><View style={{alignItems:'center'}}><Text style={s.kicker}>PHOTO → HYBRID IDENTITY</Text><Text style={s.title}>Créer une ressemblance</Text></View><View style={{width:40}}/></View><ScrollView contentContainerStyle={s.body}>
  <Text style={s.lead}>Le but n’est pas de copier ton visage en photo-réalisme. Hybrid utilise ta photo pour proposer les éléments qui se rapprochent le plus de toi, puis tu gardes le contrôle sur chaque détail.</Text>
  <View style={s.compare}><View style={s.side}><Text style={s.label}>SELFIE</Text>{uri?<Image source={{uri}} style={s.image}/>:<View style={s.empty}><Camera size={28} color="#94A3B8"/><Text style={s.emptyText}>Selfie de face, lumière naturelle</Text></View>}</View><View style={s.side}><Text style={s.label}>AVATAR HYBRID</Text><HybridAvatar2D equipped={state.equipped} size={270} expression={identity.expression} pose="neutral" background="paper" grain={identity.grain}/></View></View>
  <View style={s.actions}><SensoryPressable event="selection" onPress={()=>pick(true)} style={s.primary}><Camera size={17} color="#fff"/><Text style={s.primaryText}>Prendre une photo</Text></SensoryPressable><SensoryPressable event="selection" onPress={()=>pick(false)} style={s.secondary}><ImagePlus size={17} color="#315CFF"/><Text style={s.secondaryText}>Choisir dans la galerie</Text></SensoryPressable>{uri&&<SensoryPressable event="reward" onPress={analyze} disabled={busy} style={[s.ai,busy&&{opacity:.55}]}><BrainCircuit size={18} color="#fff"/><Text style={s.aiText}>{busy?'Analyse…':'Proposer mon avatar automatiquement'}</Text></SensoryPressable>}{uri&&<SensoryPressable event="selection" onPress={()=>{setUri(undefined);setMessage('');AsyncStorage.removeItem(KEY).catch(()=>{});update({photoAssistStatus:'idle'})}} style={s.delete}><Trash2 size={15} color="#B91C1C"/><Text style={s.deleteText}>Supprimer la photo</Text></SensoryPressable>}</View>
  {!!message&&<View style={s.message}><Sparkles size={17} color="#315CFF"/><Text style={s.messageText}>{message}</Text></View>}
  <View style={s.notice}><LockKeyhole size={19} color="#315CFF"/><View style={{flex:1}}><Text style={s.noticeTitle}>Confidentialité d’abord</Text><Text style={s.noticeText}>La photo est conservée localement par défaut. L’analyse automatique ne s’active que si un endpoint de vision sécurisé est configuré. L’app n’invente pas une analyse si aucun moteur IA n’est connecté.</Text></View></View>
  <View style={s.notice}><CheckCircle2 size={19} color="#15803D"/><View style={{flex:1}}><Text style={s.noticeTitle}>Ce que l’IA doit proposer</Text><Text style={s.noticeText}>Teint approximatif, famille de coiffure et accessoires visibles simples. Le résultat reste un avatar stylisé Hybrid, jamais une copie biométrique destinée à identifier la personne.</Text></View></View>
  <SensoryPressable event="selection" onPress={()=>{router.back();setTimeout(()=>router.push('/modals/avatar-studio' as any),100)}} style={s.done}><Text style={s.doneText}>Ouvrir le Studio et ajuster</Text></SensoryPressable>
 </ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#EEEAE3'},top:{paddingTop:54,paddingHorizontal:16,paddingBottom:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#F7F4EE',borderBottomWidth:1,borderBottomColor:'#D8D1C7'},back:{width:40,height:40,borderRadius:12,backgroundColor:'#E9E4DC',alignItems:'center',justifyContent:'center'},kicker:{fontSize:8,color:'#315CFF',fontWeight:FontWeight.extrabold,letterSpacing:1.25},title:{fontSize:18,color:Colors.textPrimary,fontWeight:FontWeight.extrabold},body:{padding:16,paddingBottom:44},lead:{fontSize:13,lineHeight:19,color:'#52627C',marginBottom:14},compare:{gap:12},side:{backgroundColor:'#F7F4EE',borderRadius:20,padding:10,borderWidth:1,borderColor:'#D8D1C7',...Shadow.sm},label:{fontSize:9,color:'#64748B',fontWeight:FontWeight.extrabold,letterSpacing:1,marginBottom:8},image:{width:'100%',height:270,borderRadius:16,backgroundColor:'#E2E8F0'},empty:{height:270,borderRadius:16,backgroundColor:'#E9E4DC',alignItems:'center',justifyContent:'center',gap:8},emptyText:{fontSize:12,color:'#64748B',fontWeight:FontWeight.bold},actions:{gap:9,marginTop:14},primary:{height:50,borderRadius:14,backgroundColor:'#111827',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},primaryText:{color:'#fff',fontWeight:FontWeight.extrabold},secondary:{height:50,borderRadius:14,backgroundColor:'#E8EEFF',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},secondaryText:{color:'#315CFF',fontWeight:FontWeight.extrabold},ai:{height:52,borderRadius:14,backgroundColor:'#315CFF',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},aiText:{color:'#fff',fontWeight:FontWeight.extrabold},delete:{alignSelf:'center',padding:10,flexDirection:'row',gap:6,alignItems:'center'},deleteText:{fontSize:11,color:'#B91C1C',fontWeight:FontWeight.bold},message:{marginTop:14,backgroundColor:'#E8EEFF',borderRadius:15,padding:12,flexDirection:'row',gap:8},messageText:{flex:1,fontSize:11,lineHeight:16,color:'#31528C',fontWeight:FontWeight.medium},notice:{marginTop:11,backgroundColor:'#F7F4EE',borderRadius:17,padding:13,flexDirection:'row',gap:10,borderWidth:1,borderColor:'#D8D1C7'},noticeTitle:{fontSize:12,color:'#111827',fontWeight:FontWeight.extrabold},noticeText:{fontSize:10.5,lineHeight:16,color:'#52627C',marginTop:3},done:{marginTop:16,height:50,borderRadius:14,backgroundColor:'#111827',alignItems:'center',justifyContent:'center'},doneText:{color:'#fff',fontWeight:FontWeight.extrabold}})
