import React, { useMemo, useState } from 'react'
import { View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import { router } from 'expo-router'
import { ArrowLeft, ChevronLeft, ChevronRight, Plus, Sparkles, CheckCircle2, Clock3 } from 'lucide-react-native'
import { Colors, FontWeight, Radius, Shadow, Spacing, SportColors } from '@/constants/theme'
import { useProfile, useSession } from '@/hooks/useProfile'
import { useActivities } from '@/hooks/useActivities'
import { buildCoachPlans } from '@/lib/coachEngine'
import { SPORTS_CONFIG } from '@/constants/sports'
import type { Activity } from '@/types/database'

function startOfWeek(d=new Date()){const x=new Date(d);x.setDate(x.getDate()-((x.getDay()+6)%7));x.setHours(0,0,0,0);return x}
const DAY=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim']
export default function CalendarScreen(){
  const insets=useSafeAreaInsets(); const {userId}=useSession(); const {profile}=useProfile(userId??undefined); const {activities}=useActivities(userId??undefined,90)
  const [offset,setOffset]=useState(0); const base=useMemo(()=>{const d=startOfWeek();d.setDate(d.getDate()+offset*7);return d},[offset])
  const days=Array.from({length:7},(_,i)=>{const d=new Date(base);d.setDate(base.getDate()+i);return d})
  const plans=useMemo(()=>buildCoachPlans(profile?.favorite_sports??[],activities as Activity[]),[profile?.favorite_sports,activities])
  const scheduled=days.map((d,i)=>({date:d,plan:plans[i%Math.max(1,plans.length)]??null,rest:i===3||(!plans.length)}))
  return <View style={[s.root,{paddingTop:insets.top}]}>
    <View style={s.header}><TouchableOpacity style={s.back} onPress={()=>router.back()}><ArrowLeft size={20} color={Colors.textPrimary}/></TouchableOpacity><View style={{flex:1}}><Text style={s.title}>Planning Hybrid</Text><Text style={s.sub}>Ta semaine d’entraînement intelligente</Text></View><TouchableOpacity style={s.add} onPress={()=>router.push('/modals/add-activity' as any)}><Plus size={19} color="#fff"/></TouchableOpacity></View>
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{paddingBottom:40}}>
      <View style={s.weekNav}><TouchableOpacity onPress={()=>setOffset(o=>o-1)}><ChevronLeft size={20} color={Colors.textSecondary}/></TouchableOpacity><View><Text style={s.weekTitle}>{base.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</Text><Text style={s.weekSub}>{base.toLocaleDateString('fr-FR',{day:'numeric',month:'short'})} — {days[6].toLocaleDateString('fr-FR',{day:'numeric',month:'short'})}</Text></View><TouchableOpacity onPress={()=>setOffset(o=>o+1)}><ChevronRight size={20} color={Colors.textSecondary}/></TouchableOpacity></View>
      <View style={s.aiCard}><View style={s.aiIcon}><Sparkles size={20} color="#7C3AED"/></View><View style={{flex:1}}><Text style={s.aiTitle}>Semaine optimisée par Coach Hybrid</Text><Text style={s.aiSub}>Réorganise les séances selon ta charge, ta récupération et tes sports.</Text></View><TouchableOpacity><Text style={s.aiLink}>Adapter</Text></TouchableOpacity></View>
      <View style={s.timeline}>{scheduled.map((item,i)=>{
        const key=item.date.toISOString().slice(0,10); const done=(activities as Activity[]).some(a=>(a.performed_at??a.created_at).slice(0,10)===key); const sport=item.plan?.sport??'running'; const cfg=SPORTS_CONFIG[sport]??SPORTS_CONFIG.running; const color=SportColors[sport]??Colors.electric
        return <View key={key} style={s.dayRow}><View style={s.dateCol}><Text style={s.dayName}>{DAY[i]}</Text><Text style={s.dayNum}>{item.date.getDate()}</Text><View style={[s.timelineDot,{backgroundColor:done?'#10B981':item.rest?'#CBD5E1':color}]}/>{i<6&&<View style={s.timelineLine}/>}</View><View style={{flex:1,paddingBottom:16}}>{item.rest?<View style={s.restCard}><Text style={s.restTitle}>Récupération</Text><Text style={s.restSub}>Mobilité légère, marche ou repos complet.</Text></View>:<TouchableOpacity style={[s.sessionCard,{borderLeftColor:color}]} activeOpacity={.9}><View style={s.sessionTop}><View style={[s.sportPill,{backgroundColor:color+'18'}]}><Text style={[s.sportPillText,{color}]}>{cfg?.labelLong??sport}</Text></View>{done?<View style={s.done}><CheckCircle2 size={14} color="#10B981"/><Text style={s.doneText}>Fait</Text></View>:<View style={s.planned}><Clock3 size={13} color={Colors.textTertiary}/><Text style={s.plannedText}>Planifié</Text></View>}</View><Text style={s.sessionTitle}>{item.plan?.title}</Text><Text style={s.sessionMeta}>{item.plan?.duration} · {item.plan?.intensity}</Text><Text style={s.sessionObjective}>{item.plan?.objective}</Text></TouchableOpacity>}</View></View>})}</View>
    </ScrollView>
  </View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},header:{height:68,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:11,backgroundColor:'#fff',borderBottomWidth:1,borderColor:Colors.borderLight},back:{width:38,height:38,borderRadius:13,backgroundColor:Colors.bgAlt,alignItems:'center',justifyContent:'center'},title:{fontSize:19,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},sub:{fontSize:10.5,color:Colors.textTertiary,marginTop:1},add:{width:38,height:38,borderRadius:13,backgroundColor:Colors.electric,alignItems:'center',justifyContent:'center'},weekNav:{margin:16,backgroundColor:'#fff',borderRadius:20,padding:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',...Shadow.sm},weekTitle:{textAlign:'center',fontWeight:FontWeight.extrabold,color:Colors.textPrimary,textTransform:'capitalize'},weekSub:{textAlign:'center',fontSize:10,color:Colors.textTertiary,marginTop:2},aiCard:{marginHorizontal:16,backgroundColor:'#F6F0FF',borderWidth:1,borderColor:'#E8DAFF',borderRadius:20,padding:14,flexDirection:'row',gap:10,alignItems:'center'},aiIcon:{width:40,height:40,borderRadius:14,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},aiTitle:{fontSize:12.5,fontWeight:FontWeight.extrabold,color:'#4C1D95'},aiSub:{fontSize:10,color:'#6D5A86',lineHeight:14,marginTop:2},aiLink:{fontSize:10.5,fontWeight:FontWeight.extrabold,color:'#7C3AED'},timeline:{paddingHorizontal:16,marginTop:18},dayRow:{flexDirection:'row'},dateCol:{width:52,alignItems:'center',position:'relative'},dayName:{fontSize:10,color:Colors.textTertiary,fontWeight:FontWeight.bold},dayNum:{fontSize:18,color:Colors.textPrimary,fontWeight:FontWeight.extrabold,marginTop:2},timelineDot:{width:10,height:10,borderRadius:5,marginTop:9,zIndex:2,borderWidth:2,borderColor:'#fff'},timelineLine:{position:'absolute',top:57,bottom:-12,width:2,backgroundColor:'#E2E8F0'},sessionCard:{backgroundColor:'#fff',borderRadius:18,padding:14,borderLeftWidth:4,...Shadow.sm},restCard:{backgroundColor:'#F1F5F9',borderRadius:18,padding:14,borderWidth:1,borderColor:'#E2E8F0'},restTitle:{fontWeight:FontWeight.extrabold,color:Colors.textSecondary},restSub:{fontSize:10.5,color:Colors.textTertiary,marginTop:4},sessionTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},sportPill:{paddingHorizontal:8,paddingVertical:5,borderRadius:99},sportPillText:{fontSize:9,fontWeight:FontWeight.extrabold},done:{flexDirection:'row',gap:4,alignItems:'center'},doneText:{fontSize:9,color:'#10B981',fontWeight:FontWeight.bold},planned:{flexDirection:'row',gap:4,alignItems:'center'},plannedText:{fontSize:9,color:Colors.textTertiary,fontWeight:FontWeight.bold},sessionTitle:{fontSize:14,fontWeight:FontWeight.extrabold,color:Colors.textPrimary,marginTop:10},sessionMeta:{fontSize:10.5,color:Colors.textSecondary,marginTop:3},sessionObjective:{fontSize:10.5,color:Colors.textTertiary,lineHeight:15,marginTop:7}})
