import React,{useMemo,useState}from'react'
import{View,Text,StyleSheet,ScrollView,TouchableOpacity,SafeAreaView}from'react-native'
import{LinearGradient}from'expo-linear-gradient'
import{router}from'expo-router'
import*as Haptics from'expo-haptics'
import{Dumbbell,Footprints,Zap,Target,Users,Shield,Mountain,Sparkles,Check,ChevronLeft}from'lucide-react-native'
import{ATHLETE_CLASSES,type AthleteClassKey}from'@/constants/v5'
import{Colors,FontWeight,Shadow,Spacing}from'@/constants/theme'
import{useProgression}from'@/hooks/useProgression'
import{useProfile,useSession}from'@/hooks/useProfile'
import{supabase}from'@/lib/supabase'
import{RewardBurst}from'@/components/v5/RewardBurst'
const ICONS:any={Dumbbell,Footprints,Zap,Target,Users,Shield,Mountain,Sparkles}
export default function ChooseClass(){const{userId}=useSession();const{profile}=useProfile(userId??undefined);const prog=useProgression();const initial=((profile as any)?.athlete_class??prog.athleteClass??'hybrid')as AthleteClassKey;const[selected,setSelected]=useState<AthleteClassKey>(initial);const[done,setDone]=useState(false);const c=useMemo(()=>ATHLETE_CLASSES.find(x=>x.key===selected)!,[selected])
 const save=async()=>{Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(()=>{});prog.setAthleteClass(selected);if(userId)await supabase.from('profiles').update({athlete_class:selected}).eq('id',userId);setDone(true)}
 return <SafeAreaView style={s.safe}><LinearGradient colors={['#081226','#172554','#315CFF']} style={s.hero}><TouchableOpacity style={s.back} onPress={()=>router.back()}><ChevronLeft size={22} color="#fff"/></TouchableOpacity><Text style={s.kicker}>IDENTITÉ V5</Text><Text style={s.title}>Choisis ta classe</Text><Text style={s.sub}>Ta classe personnalise ton expérience, tes missions et ton Coach. Elle n’augmente jamais artificiellement tes performances.</Text></LinearGradient><ScrollView contentContainerStyle={s.content}>{ATHLETE_CLASSES.map(x=>{const Icon=ICONS[x.icon]??Sparkles;const on=x.key===selected;return <TouchableOpacity key={x.key} activeOpacity={.88} onPress={()=>{setSelected(x.key);Haptics.selectionAsync().catch(()=>{})}} style={[s.card,on&&{borderColor:x.color,borderWidth:2}]}><LinearGradient colors={on?[x.color+'20',x.color2+'0E']:['#fff','#fff']} style={s.cardInner}><View style={[s.icon,{backgroundColor:x.color+'18'}]}><Icon size={23} color={x.color}/></View><View style={{flex:1}}><View style={s.row}><Text style={s.name}>{x.name}</Text>{on?<View style={[s.check,{backgroundColor:x.color}]}><Check size={12} color="#fff"/></View>:null}</View><Text style={[s.subtitle,{color:x.color}]}>{x.subtitle}</Text><Text style={s.desc}>{x.description}</Text><View style={[s.boost,{backgroundColor:x.color+'12'}]}><Text style={[s.boostText,{color:x.color}]}>{x.boostLabel}</Text></View></View></LinearGradient></TouchableOpacity>})}<TouchableOpacity style={s.save} onPress={save}><LinearGradient colors={[c.color,c.color2]} style={s.saveInner}><Text style={s.saveText}>Devenir {c.name}</Text></LinearGradient></TouchableOpacity><Text style={s.note}>Tu pourras changer de classe plus tard. Les classements restent basés uniquement sur des performances vérifiées.</Text></ScrollView><RewardBurst visible={done} title={`Classe ${c.name} activée`} subtitle={`${c.boostLabel} · nouvelles missions et recommandations débloquées`} xp={100} onClose={()=>{prog.addXp(100,'class:first');setDone(false);router.back()}}/></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.bg},hero:{paddingHorizontal:20,paddingTop:14,paddingBottom:22},back:{width:38,height:38,borderRadius:13,backgroundColor:'rgba(255,255,255,.1)',alignItems:'center',justifyContent:'center',marginBottom:18},kicker:{fontSize:9,color:'#93C5FD',fontWeight:FontWeight.extrabold,letterSpacing:1.6},title:{fontSize:30,color:'#fff',fontWeight:FontWeight.extrabold,marginTop:5},sub:{fontSize:12,color:'#D8E1FF',lineHeight:18,marginTop:7,maxWidth:520},content:{padding:Spacing.md,gap:10,paddingBottom:48},card:{borderRadius:20,backgroundColor:'#fff',...Shadow.sm},cardInner:{borderRadius:18,padding:14,flexDirection:'row',gap:12},icon:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center'},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},name:{fontSize:16,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},check:{width:22,height:22,borderRadius:7,alignItems:'center',justifyContent:'center'},subtitle:{fontSize:10.5,fontWeight:FontWeight.extrabold,marginTop:1},desc:{fontSize:10.5,color:Colors.textSecondary,lineHeight:15,marginTop:5},boost:{alignSelf:'flex-start',paddingHorizontal:8,paddingVertical:5,borderRadius:99,marginTop:8},boostText:{fontSize:9,fontWeight:FontWeight.extrabold},save:{borderRadius:18,overflow:'hidden',marginTop:8,...Shadow.md},saveInner:{paddingVertical:15,alignItems:'center'},saveText:{color:'#fff',fontWeight:FontWeight.extrabold,fontSize:14},note:{fontSize:9.5,color:Colors.textTertiary,textAlign:'center',lineHeight:14,paddingHorizontal:10}})
