import React,{useMemo,useState}from'react'
import{View,Text,StyleSheet,ScrollView,TextInput}from'react-native'
import{router}from'expo-router'
import{ChevronLeft,Trophy,Timer,CheckCircle2,Circle,Music2,MapPin,BrainCircuit}from'lucide-react-native'
import{SensoryPressable}from'@/components/v6/SensoryPressable'
import{useActivities}from'@/hooks/useActivities'
import{useSession}from'@/hooks/useProfile'
import{buildHybridIntelligence}from'@/lib/v10/intelligence'
import{Colors,Shadow}from'@/constants/theme'

const CHECKS=['Dossard / inscription','Montre chargée','Tenue + chaussures','Hydratation / nutrition','Échauffement planifié']
export default function CompetitionMode(){const{userId}=useSession();const{activities}=useActivities(userId??undefined,90);const intel=useMemo(()=>buildHybridIntelligence(activities),[activities]);const[name,setName]=useState('Prochaine compétition');const[target,setTarget]=useState('');const[done,setDone]=useState<number[]>([]);return <View style={s.root}><View style={s.header}><SensoryPressable onPress={()=>router.back()} event="tap" style={s.back}><ChevronLeft size={21}/></SensoryPressable><View><Text style={s.kicker}>RACE / MATCH DAY</Text><Text style={s.h1}>Mode compétition</Text></View></View><ScrollView contentContainerStyle={s.content}><View style={s.hero}><Trophy size={33} color="#FBBF24"/><TextInput value={name} onChangeText={setName} style={s.name}/><Text style={s.form}>État actuel · {intel.state.toUpperCase()} · Forme {intel.form}/100</Text><View style={s.targetRow}><Timer size={17} color="#60A5FA"/><TextInput value={target} onChangeText={setTarget} placeholder="Objectif : ex. 39:59 / gagner 2 sets" placeholderTextColor="#64748B" style={s.target}/></View></View><Text style={s.section}>STRATÉGIE AUTOMATIQUE</Text><View style={s.card}><BrainCircuit size={19} color="#7C3AED"/><Text style={s.cardTitle}>Conseil Hybrid</Text><Text style={s.body}>{intel.fatigue>70?'Ta fatigue est haute. Réduis l’échauffement et n’ajoute pas de charge inutile avant l’épreuve.':intel.form>80?'Ta forme est haute. Garde ton plan et évite de changer ta stratégie au dernier moment.':'Reste conservateur au départ et garde une marge pour la deuxième moitié / fin de match.'}</Text></View><Text style={s.section}>CHECKLIST</Text>{CHECKS.map((x,i)=>{const ok=done.includes(i);return <SensoryPressable key={x} event="selection" onPress={()=>setDone(p=>ok?p.filter(v=>v!==i):[...p,i])} style={s.check}>{ok?<CheckCircle2 size={20} color="#10B981"/>:<Circle size={20} color="#94A3B8"/>}<Text style={[s.checkText,ok&&{textDecorationLine:'line-through',color:'#94A3B8'}]}>{x}</Text></SensoryPressable>})}<Text style={s.section}>RACCOURCIS</Text><View style={s.actions}><SensoryPressable event="tap" onPress={()=>router.push('/modals/music-space' as any)} style={s.action}><Music2 size={20} color="#7C3AED"/><Text style={s.actionText}>Musique</Text></SensoryPressable><SensoryPressable event="tap" onPress={()=>router.push('/modals/track' as any)} style={s.action}><MapPin size={20} color="#2563EB"/><Text style={s.actionText}>Démarrer le tracking</Text></SensoryPressable></View></ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#F4F7FB'},header:{paddingTop:56,paddingHorizontal:16,paddingBottom:12,flexDirection:'row',alignItems:'center',gap:10},back:{width:38,height:38,borderRadius:13,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',...Shadow.sm},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:'#D97706'},h1:{fontSize:24,fontWeight:'900',color:Colors.textPrimary},content:{padding:16,paddingBottom:44},hero:{backgroundColor:'#0B1220',borderRadius:26,padding:19,alignItems:'center',...Shadow.md},name:{fontSize:22,fontWeight:'900',color:'#fff',textAlign:'center',marginTop:9,minWidth:220},form:{fontSize:10.5,color:'#94A3B8',marginTop:5},targetRow:{marginTop:14,backgroundColor:'#111C2F',borderRadius:15,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:7,width:'100%'},target:{flex:1,color:'#fff',fontSize:11.5,paddingVertical:11},section:{fontSize:10,fontWeight:'900',letterSpacing:1.1,color:Colors.textTertiary,marginTop:20,marginBottom:8},card:{backgroundColor:'#fff',borderRadius:18,padding:14,...Shadow.sm},cardTitle:{fontWeight:'900',fontSize:13,color:Colors.textPrimary,marginTop:7},body:{fontSize:11,lineHeight:17,color:Colors.textSecondary,marginTop:5},check:{backgroundColor:'#fff',borderRadius:15,padding:12,marginBottom:7,flexDirection:'row',gap:10,alignItems:'center',...Shadow.sm},checkText:{fontSize:12,color:Colors.textPrimary,fontWeight:'700'},actions:{flexDirection:'row',gap:8},action:{flex:1,backgroundColor:'#fff',borderRadius:17,padding:14,alignItems:'center',gap:7,...Shadow.sm},actionText:{fontSize:10.5,fontWeight:'800',color:Colors.textPrimary,textAlign:'center'}})
