import React,{useCallback,useEffect,useState}from'react'
import{View,Text,StyleSheet,ScrollView,TouchableOpacity,Alert,ActivityIndicator}from'react-native'
import{router}from'expo-router'
import{Colors,FontSize,FontWeight,Radius,Spacing}from'@/constants/theme'
import{useSession}from'@/hooks/useProfile'
import{supabase}from'@/lib/supabase'

type Provider='garmin'|'apple_health'|'health_connect'|'strava'|'spotify'|'apple_music'
const PROVIDERS:{id:Provider;name:string;emoji:string;note:string}[]=[
 {id:'garmin',name:'Garmin',emoji:'⌚',note:'OAuth Garmin Health API requis côté serveur.'},
 {id:'apple_health',name:'Apple Health',emoji:'🍎',note:'Nécessite HealthKit et un build natif iOS.'},
 {id:'health_connect',name:'Health Connect',emoji:'🤖',note:'Nécessite Health Connect et un build natif Android.'},
 {id:'strava',name:'Strava',emoji:'🟠',note:'OAuth Strava + webhook recommandé.'},
 {id:'spotify',name:'Spotify',emoji:'🎵',note:'OAuth Spotify requis pour afficher le morceau en cours et créer le soundtrack de la séance.'},
 {id:'apple_music',name:'Apple Music',emoji:'🎧',note:'MusicKit requis pour relier la musique à l’Activity Story.'},
]
export default function ConnectionsScreen(){const{userId}=useSession();const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true);const load=useCallback(async()=>{if(!userId)return;setLoading(true);const{data}=await supabase.from('connected_sources').select('*').eq('user_id',userId);setRows(data??[]);setLoading(false)},[userId]);useEffect(()=>{load()},[load]);const status=(id:Provider)=>rows.find(r=>r.provider===id)?.status??'disconnected';const press=(p:typeof PROVIDERS[number])=>{if(status(p.id)==='connected')Alert.alert(p.name,'Cette source est marquée connectée. La déconnexion doit aussi révoquer le token chez le fournisseur.');else Alert.alert(`Connecter ${p.name}`,`${p.note}\n\nLe modèle de données et l’import idempotent sont prêts dans le projet. Il reste à renseigner les identifiants développeur du fournisseur et le flux OAuth/natif.`)};return <View style={s.root}><View style={s.head}><TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>← Retour</Text></TouchableOpacity><Text style={s.title}>Sources de données</Text><Text style={s.sub}>Les imports externes seront marqués vérifiés et ne seront pas dupliqués.</Text></View>{loading?<ActivityIndicator color={Colors.electric}/>:<ScrollView contentContainerStyle={s.content}>{PROVIDERS.map(p=>{const st=status(p.id);return <TouchableOpacity key={p.id} style={s.card} onPress={()=>press(p)}><Text style={s.emoji}>{p.emoji}</Text><View style={{flex:1}}><Text style={s.name}>{p.name}</Text><Text style={s.note}>{p.note}</Text></View><View style={[s.badge,st==='connected'&&s.badgeOn]}><Text style={[s.badgeText,st==='connected'&&s.badgeTextOn]}>{st==='connected'?'Connecté':'À configurer'}</Text></View></TouchableOpacity>})}<View style={s.info}><Text style={s.infoTitle}>Architecture prête</Text><Text style={s.note}>Le projet contient désormais les champs source, identifiant externe, activité vérifiée et un helper d’import commun. Les secrets OAuth ne doivent jamais être placés dans l’app mobile.</Text></View></ScrollView>}</View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},head:{paddingTop:54,paddingHorizontal:Spacing.md,paddingBottom:12},back:{color:Colors.electric,fontWeight:FontWeight.semibold,marginBottom:10},title:{fontSize:FontSize.xl,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},sub:{color:Colors.textSecondary,marginTop:5,lineHeight:20},content:{padding:Spacing.md,gap:Spacing.sm,paddingBottom:50},card:{backgroundColor:Colors.bgCard,borderRadius:Radius.lg,padding:Spacing.md,flexDirection:'row',alignItems:'center',gap:12},emoji:{fontSize:28},name:{fontWeight:FontWeight.bold,color:Colors.textPrimary},note:{fontSize:FontSize.xs,color:Colors.textSecondary,lineHeight:18,marginTop:3},badge:{paddingHorizontal:8,paddingVertical:5,borderRadius:Radius.full,backgroundColor:Colors.bgAlt},badgeOn:{backgroundColor:'rgba(18,183,106,.12)'},badgeText:{fontSize:10,color:Colors.textTertiary,fontWeight:FontWeight.bold},badgeTextOn:{color:Colors.success},info:{backgroundColor:Colors.electricDim,borderRadius:Radius.lg,padding:Spacing.md,marginTop:Spacing.sm},infoTitle:{fontWeight:FontWeight.bold,color:Colors.electric,marginBottom:4}})
