import React,{useState}from'react'
import{SafeAreaView,View,Text,StyleSheet,TouchableOpacity,ScrollView,Alert}from'react-native'
import{router}from'expo-router'
import{ChevronLeft,ShieldCheck,Send}from'lucide-react-native'
import{SPORT_CATALOG}from'@/constants/sportCatalog'
import{COMPETITIVE_LEVELS}from'@/constants/v5'
import{Colors,FontWeight,Shadow,Spacing}from'@/constants/theme'
import{useSession}from'@/hooks/useProfile'
import{supabase}from'@/lib/supabase'
export default function Credentials(){const{userId}=useSession();const[sport,setSport]=useState('badminton');const[level,setLevel]=useState<string>('Régional');const submit=async()=>{if(!userId)return;const{error}=await supabase.from('sport_credentials').insert({user_id:userId,sport_type:sport,level_label:level,status:'pending',verified:false});if(error)Alert.alert('Impossible',error.message);else Alert.alert('Demande envoyée','Le niveau apparaîtra dans les classements officiels après vérification.')};return <SafeAreaView style={s.safe}><View style={s.head}><TouchableOpacity style={s.back} onPress={()=>router.back()}><ChevronLeft size={21} color={Colors.textPrimary}/></TouchableOpacity><View style={{flex:1}}><Text style={s.title}>Niveau sportif</Text><Text style={s.sub}>Déclaration + vérification</Text></View><ShieldCheck size={22} color="#10B981"/></View><ScrollView contentContainerStyle={s.content}><View style={s.info}><Text style={s.infoTitle}>Pourquoi vérifier ?</Text><Text style={s.infoText}>Un niveau “National 2”, “Élite” ou fédéral ne doit pas être auto-déclaré dans le classement. Tu peux l’envoyer ici ; il reste “en attente” jusqu’à validation par justificatif ou organisme partenaire.</Text></View><Text style={s.section}>Sport</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{SPORT_CATALOG.filter((x:any)=>['racket','team_ball','combat','aquatic','athletics_gymnastics'].includes(x.family)).slice(0,36).map((sp:any)=><TouchableOpacity key={sp.key} style={[s.chip,sport===sp.key&&{backgroundColor:sp.color,borderColor:sp.color}]} onPress={()=>setSport(sp.key)}><Text style={[s.chipText,sport===sp.key&&{color:'#fff'}]}>{sp.label}</Text></TouchableOpacity>)}</ScrollView><Text style={s.section}>Niveau</Text><View style={s.levels}>{COMPETITIVE_LEVELS.map(l=><TouchableOpacity key={l} style={[s.level,level===l&&s.levelOn]} onPress={()=>setLevel(l)}><Text style={[s.levelText,level===l&&s.levelTextOn]}>{l}</Text>{level===l?<ShieldCheck size={14} color="#315CFF"/>:null}</TouchableOpacity>)}</View><TouchableOpacity style={s.send} onPress={submit}><Send size={17} color="#fff"/><Text style={s.sendText}>Envoyer pour vérification</Text></TouchableOpacity><Text style={s.note}>En production, cette étape pourra accepter une licence, un classement fédéral ou une connexion partenaire. Les faux justificatifs devront pouvoir être signalés et retirés.</Text></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.bg},head:{flexDirection:'row',alignItems:'center',gap:12,padding:Spacing.md},back:{width:40,height:40,borderRadius:13,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',...Shadow.sm},title:{fontSize:20,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},sub:{fontSize:10,color:Colors.textTertiary},content:{padding:Spacing.md,gap:12,paddingBottom:50},info:{backgroundColor:'#ECFDF5',borderRadius:18,padding:14},infoTitle:{fontSize:12,fontWeight:FontWeight.extrabold,color:'#065F46'},infoText:{fontSize:10,color:'#047857',lineHeight:15,marginTop:4},section:{fontSize:13,fontWeight:FontWeight.extrabold,color:Colors.textPrimary,marginTop:3},chips:{gap:7,paddingRight:12},chip:{backgroundColor:'#fff',borderWidth:1,borderColor:Colors.border,paddingHorizontal:11,paddingVertical:8,borderRadius:99},chipText:{fontSize:10,color:Colors.textSecondary,fontWeight:FontWeight.bold},levels:{gap:7},level:{backgroundColor:'#fff',borderRadius:14,paddingHorizontal:13,paddingVertical:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderWidth:1,borderColor:Colors.border},levelOn:{borderColor:'#A5B4FC',backgroundColor:'#EEF2FF'},levelText:{fontSize:11,color:Colors.textSecondary,fontWeight:FontWeight.bold},levelTextOn:{color:'#315CFF'},send:{backgroundColor:'#111827',borderRadius:16,paddingVertical:14,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:5},sendText:{color:'#fff',fontWeight:FontWeight.extrabold,fontSize:12},note:{fontSize:9.5,color:Colors.textTertiary,lineHeight:14,textAlign:'center'}})
