import React from 'react'
import{View,Text,StyleSheet,ScrollView}from'react-native'
import{router}from'expo-router'
import{ChevronLeft,Brain,Activity,Clock3,TrendingUp,BarChart3}from'lucide-react-native'
import{Colors,FontWeight,Shadow,Spacing}from'@/constants/theme'
import{useSession,useProfile}from'@/hooks/useProfile'
import{useActivities}from'@/hooks/useActivities'
import{useLifeCheckin}from'@/hooks/useLifeCheckin'
import{useAdaptiveOS}from'@/hooks/v12/useAdaptiveOS'
import{SensoryPressable}from'@/components/v6/SensoryPressable'
export default function DigitalTwin(){const{userId}=useSession();const{profile}=useProfile(userId??undefined);const{activities}=useActivities(userId??undefined,3650);const{checkin}=useLifeCheckin(userId??undefined);const{snapshot}=useAdaptiveOS(activities,profile?.favorite_sports??[],checkin);return <View style={s.root}><View style={s.header}><SensoryPressable onPress={()=>router.back()} style={s.back}><ChevronLeft size={21}/></SensoryPressable><View><Text style={s.eyebrow}>DIGITAL TWIN</Text><Text style={s.title}>Ton modèle sportif</Text></View></View><ScrollView contentContainerStyle={s.wrap}><View style={s.hero}><Brain size={27} color="#fff"/><Text style={s.heroTitle}>Hybrid apprend comment TU réagis.</Text><Text style={s.heroSub}>Ce modèle ne te compare pas seulement à une moyenne : il construit progressivement ta baseline personnelle à partir de tes propres séances.</Text></View>{snapshot.twin.map((x,i)=><View key={i} style={s.card}><View style={s.cardTop}><View style={s.icon}>{i===0?<Activity size={18} color={Colors.electric}/>:i===1?<BarChart3 size={18} color={Colors.violet}/>:i===2?<TrendingUp size={18} color={Colors.warning}/>:<Clock3 size={18} color={Colors.success}/>}</View><View style={{flex:1}}><Text style={s.cardTitle}>{x.title}</Text><Text style={s.value}>{x.value}</Text></View><Text style={s.conf}>{x.confidence}%</Text></View><Text style={s.detail}>{x.detail}</Text></View>)}<View style={s.forecast}><Text style={s.section}>Projection de charge</Text><View style={s.bars}>{snapshot.loadForecast.map((v,i)=>{const max=Math.max(...snapshot.loadForecast,1);return <View key={i} style={s.barCol}><View style={[s.bar,{height:22+60*v/max}]}/><Text style={s.barLabel}>S{i+1}</Text></View>})}</View><Text style={s.note}>Projection indicative, pas une promesse de performance. Elle sert à visualiser la direction du plan.</Text></View><SensoryPressable onPress={()=>router.push('/modals/scenario-lab' as any)} style={s.cta}><Text style={s.ctaText}>Tester un scénario “Et si… ?”</Text></SensoryPressable></ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},header:{paddingTop:54,paddingHorizontal:16,paddingBottom:10,flexDirection:'row',gap:10,alignItems:'center'},back:{width:38,height:38,borderRadius:13,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',...Shadow.sm},eyebrow:{fontSize:8.5,color:Colors.violet,fontWeight:FontWeight.extrabold,letterSpacing:1.2},title:{fontSize:21,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},wrap:{padding:Spacing.md,gap:10,paddingBottom:70},hero:{backgroundColor:'#111827',borderRadius:24,padding:17,gap:8},heroTitle:{fontSize:18,color:'#fff',fontWeight:FontWeight.extrabold},heroSub:{fontSize:10.5,color:'#CBD5E1',lineHeight:16},card:{backgroundColor:'#fff',borderRadius:18,padding:13,...Shadow.sm},cardTop:{flexDirection:'row',alignItems:'center',gap:9},icon:{width:38,height:38,borderRadius:12,backgroundColor:'#F4F7FB',alignItems:'center',justifyContent:'center'},cardTitle:{fontSize:10,color:Colors.textSecondary,fontWeight:FontWeight.bold},value:{fontSize:17,color:Colors.textPrimary,fontWeight:FontWeight.extrabold,marginTop:1},conf:{fontSize:9,color:Colors.textTertiary},detail:{fontSize:9.5,color:Colors.textSecondary,lineHeight:14,marginTop:8},forecast:{backgroundColor:'#fff',borderRadius:18,padding:14},section:{fontSize:13,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},bars:{height:110,flexDirection:'row',alignItems:'flex-end',gap:8,marginTop:12},barCol:{flex:1,alignItems:'center',justifyContent:'flex-end'},bar:{width:'72%',backgroundColor:Colors.electric,borderRadius:8},barLabel:{fontSize:8,color:Colors.textTertiary,marginTop:5},note:{fontSize:9,color:Colors.textTertiary,lineHeight:13,marginTop:9},cta:{height:46,borderRadius:15,backgroundColor:Colors.violet,alignItems:'center',justifyContent:'center'},ctaText:{color:'#fff',fontSize:11.5,fontWeight:FontWeight.extrabold}})
