import React, { useMemo, useState } from 'react'
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, TextInput, Modal } from 'react-native'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import { router } from 'expo-router'
import { ArrowLeft, Plus, Footprints, Bike, CircleDot, Watch, Package, Gauge, AlertTriangle, CheckCircle2 } from 'lucide-react-native'
import { Colors, FontWeight, Shadow } from '@/constants/theme'
import { useActivities } from '@/hooks/useActivities'
import { useSession } from '@/hooks/useProfile'
import type { Activity } from '@/types/database'

const ICONS:any={shoes:Footprints,bike:Bike,racket:CircleDot,watch:Watch,other:Package}
const START=[
 {id:'1',category:'shoes',name:'Chaussures principales',brand:'Running',distance_km:432,threshold_km:650,active:true},
 {id:'2',category:'racket',name:'Raquette compétition',brand:'Badminton',distance_km:0,usage_minutes:1980,threshold_km:null,active:true},
]
export default function EquipmentScreen(){
 const insets=useSafeAreaInsets(); const {userId}=useSession(); const {activities}=useActivities(userId??undefined,3650); const [items,setItems]=useState<any[]>(START); const [open,setOpen]=useState(false); const [name,setName]=useState(''); const [category,setCategory]=useState('shoes')
 const totalDistance=useMemo(()=>(activities as Activity[]).reduce((s,a)=>s+Number(a.metrics?.distance_km??a.metrics?.distance??0),0),[activities])
 const add=()=>{if(!name.trim())return;setItems(x=>[{id:String(Date.now()),category,name:name.trim(),brand:'',distance_km:0,threshold_km:category==='shoes'?650:null,active:true},...x]);setName('');setOpen(false)}
 return <View style={[s.root,{paddingTop:insets.top}]}><View style={s.header}><TouchableOpacity style={s.back} onPress={()=>router.back()}><ArrowLeft size={20} color={Colors.textPrimary}/></TouchableOpacity><View style={{flex:1}}><Text style={s.title}>Équipement</Text><Text style={s.sub}>Suis l’usure de ton matériel sportif</Text></View><TouchableOpacity style={s.add} onPress={()=>setOpen(true)}><Plus size={19} color="#fff"/></TouchableOpacity></View><ScrollView contentContainerStyle={{paddingBottom:40}} showsVerticalScrollIndicator={false}>
   <View style={s.hero}><View><Text style={s.heroLabel}>DISTANCE TOTALE SUIVIE</Text><Text style={s.heroValue}>{Math.round(totalDistance)} km</Text><Text style={s.heroSub}>Hybrid peut attribuer automatiquement tes activités au matériel utilisé.</Text></View><View style={s.heroIcon}><Gauge size={27} color="#4B7BFF"/></View></View>
   <Text style={s.section}>Matériel actif</Text>{items.map(item=><EquipmentCard key={item.id} item={item}/>) }
   <View style={s.tip}><AlertTriangle size={18} color="#F59E0B"/><Text style={s.tipText}>Les seuils d’usure sont des repères configurables, pas des règles médicales ou de sécurité absolues.</Text></View>
 </ScrollView>
 <Modal visible={open} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><View style={s.modalBg}><View style={[s.sheet,{paddingBottom:Math.max(20,insets.bottom)}]}><Text style={s.sheetTitle}>Ajouter un équipement</Text><TextInput value={name} onChangeText={setName} placeholder="Ex. Nike Pegasus 41" placeholderTextColor={Colors.textTertiary} style={s.input}/><View style={s.cats}>{['shoes','bike','racket','watch','other'].map(c=>{const I=ICONS[c];return <TouchableOpacity key={c} style={[s.cat,category===c&&s.catActive]} onPress={()=>setCategory(c)}><I size={19} color={category===c?Colors.electric:Colors.textTertiary}/></TouchableOpacity>})}</View><TouchableOpacity style={s.save} onPress={add}><Text style={s.saveText}>Ajouter</Text></TouchableOpacity><TouchableOpacity style={s.cancel} onPress={()=>setOpen(false)}><Text style={s.cancelText}>Annuler</Text></TouchableOpacity></View></View></Modal>
 </View>
}
function EquipmentCard({item}:{item:any}){const I=ICONS[item.category]??Package; const progress=item.threshold_km?Math.min(1,(item.distance_km??0)/item.threshold_km):Math.min(1,(item.usage_minutes??0)/(60*50)); const warning=progress>=.8;return <View style={s.card}><View style={[s.itemIcon,{backgroundColor:warning?'#FFF7E7':'#EEF2FF'}]}><I size={23} color={warning?'#F59E0B':'#4B7BFF'}/></View><View style={{flex:1}}><View style={s.cardTop}><Text style={s.itemName}>{item.name}</Text>{warning?<AlertTriangle size={16} color="#F59E0B"/>:<CheckCircle2 size={16} color="#10B981"/>}</View><Text style={s.brand}>{item.brand||'Équipement Hybrid'}</Text><View style={s.track}><View style={[s.fill,{width:`${Math.max(3,progress*100)}%`,backgroundColor:warning?'#F59E0B':'#4B7BFF'}]}/></View><Text style={s.usage}>{item.threshold_km?`${item.distance_km} / ${item.threshold_km} km`:`${Math.round((item.usage_minutes??0)/60)} h d’utilisation`}</Text></View></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},header:{height:68,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:11,backgroundColor:'#fff',borderBottomWidth:1,borderColor:Colors.borderLight},back:{width:38,height:38,borderRadius:13,backgroundColor:Colors.bgAlt,alignItems:'center',justifyContent:'center'},title:{fontSize:19,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},sub:{fontSize:10.5,color:Colors.textTertiary,marginTop:1},add:{width:38,height:38,borderRadius:13,backgroundColor:Colors.electric,alignItems:'center',justifyContent:'center'},hero:{margin:16,backgroundColor:'#0D1833',borderRadius:24,padding:18,flexDirection:'row',alignItems:'center',...Shadow.md},heroLabel:{fontSize:9,color:'#93C5FD',fontWeight:FontWeight.extrabold,letterSpacing:1.1},heroValue:{fontSize:31,color:'#fff',fontWeight:FontWeight.extrabold,marginTop:3},heroSub:{fontSize:10.5,color:'#CBD5E1',lineHeight:15,marginTop:4,maxWidth:240},heroIcon:{width:50,height:50,borderRadius:16,backgroundColor:'rgba(255,255,255,.08)',alignItems:'center',justifyContent:'center'},section:{fontSize:13,fontWeight:FontWeight.extrabold,color:Colors.textPrimary,marginHorizontal:16,marginBottom:9},card:{marginHorizontal:16,marginBottom:10,backgroundColor:'#fff',borderRadius:20,padding:14,flexDirection:'row',gap:12,...Shadow.sm},itemIcon:{width:48,height:48,borderRadius:15,alignItems:'center',justifyContent:'center'},cardTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},itemName:{fontSize:13,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},brand:{fontSize:10,color:Colors.textTertiary,marginTop:2},track:{height:6,backgroundColor:Colors.bgAlt,borderRadius:99,overflow:'hidden',marginTop:10},fill:{height:'100%',borderRadius:99},usage:{fontSize:9.5,color:Colors.textTertiary,marginTop:4},tip:{margin:16,backgroundColor:'#FFFBEB',borderRadius:16,padding:12,flexDirection:'row',gap:9,alignItems:'flex-start'},tipText:{flex:1,fontSize:10,color:'#92400E',lineHeight:15},modalBg:{flex:1,backgroundColor:'rgba(8,18,38,.45)',justifyContent:'flex-end'},sheet:{backgroundColor:'#fff',borderTopLeftRadius:28,borderTopRightRadius:28,padding:20},sheetTitle:{fontSize:20,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},input:{height:48,borderWidth:1,borderColor:Colors.border,borderRadius:14,paddingHorizontal:13,marginTop:15,color:Colors.textPrimary},cats:{flexDirection:'row',gap:8,marginTop:12},cat:{flex:1,height:47,borderRadius:14,backgroundColor:Colors.bg,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:Colors.borderLight},catActive:{borderColor:Colors.electric,backgroundColor:Colors.electricDim},save:{backgroundColor:Colors.electric,borderRadius:15,paddingVertical:14,alignItems:'center',marginTop:15},saveText:{color:'#fff',fontWeight:FontWeight.extrabold},cancel:{alignItems:'center',padding:12},cancelText:{color:Colors.textSecondary,fontWeight:FontWeight.bold}})
