import React,{useEffect,useMemo,useState}from'react'
import{View,Text,StyleSheet,ScrollView,TextInput}from'react-native'
import AsyncStorage from'@react-native-async-storage/async-storage'
import{router}from'expo-router'
import{ChevronLeft,BookOpen,Plus,Sparkles}from'lucide-react-native'
import{Colors,FontWeight,Shadow,Spacing}from'@/constants/theme'
import{SensoryPressable}from'@/components/v6/SensoryPressable'
type Entry={id:string;text:string;createdAt:string;tags:string[]}
const KEY='hybrid:v12:journal'
function tagsFor(t:string){const x=t.toLowerCase(),tags:string[]=[];if(/jamb|lourd|courb|fatigu/.test(x))tags.push('fatigue');if(/sommeil|dormi|nuit/.test(x))tags.push('sommeil');if(/motivé|motivation|envie|mental|stress/.test(x))tags.push('mental');if(/douleur|mal |gêne/.test(x))tags.push('douleur');if(/super|fort|facile|excellent|bien/.test(x))tags.push('positif');if(/compét|match|course|tournoi/.test(x))tags.push('compétition');return tags.length?tags:['journal']}
export default function Journal(){const[text,setText]=useState('');const[entries,setEntries]=useState<Entry[]>([]);useEffect(()=>{AsyncStorage.getItem(KEY).then(x=>{if(x)try{setEntries(JSON.parse(x))}catch{}})},[]);const save=()=>{if(!text.trim())return;const next=[{id:String(Date.now()),text:text.trim(),createdAt:new Date().toISOString(),tags:tagsFor(text)},...entries];setEntries(next);setText('');AsyncStorage.setItem(KEY,JSON.stringify(next)).catch(()=>{})};const insight=useMemo(()=>{const recent=entries.slice(0,10);const counts:Record<string,number>={};recent.flatMap(e=>e.tags).forEach(t=>counts[t]=(counts[t]??0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];return top?`Signal récent dominant : ${top[0]} (${top[1]} mention${top[1]>1?'s':''}). Hybrid pourra croiser ce contexte avec tes séances.`:'Écris quelques notes : Hybrid commencera à repérer les thèmes qui reviennent.'},[entries]);return <View style={s.root}><View style={s.header}><SensoryPressable onPress={()=>router.back()} style={s.back}><ChevronLeft size={21}/></SensoryPressable><View><Text style={s.eyebrow}>SMART JOURNAL</Text><Text style={s.title}>Journal sportif</Text></View></View><ScrollView contentContainerStyle={s.wrap}><View style={s.insight}><Sparkles size={18} color={Colors.violet}/><Text style={s.insightText}>{insight}</Text></View><View style={s.composer}><TextInput value={text} onChangeText={setText} multiline placeholder="Ex. Jambes lourdes aujourd’hui, mais j’ai bien dormi…" placeholderTextColor={Colors.textTertiary} style={s.input}/><SensoryPressable onPress={save} style={s.add} event="success"><Plus size={18} color="#fff"/><Text style={s.addText}>Ajouter</Text></SensoryPressable></View><Text style={s.section}>Historique</Text>{entries.map(e=><View key={e.id} style={s.entry}><View style={s.entryTop}><BookOpen size={15} color={Colors.electric}/><Text style={s.date}>{new Date(e.createdAt).toLocaleString('fr-FR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</Text></View><Text style={s.entryText}>{e.text}</Text><View style={s.tags}>{e.tags.map(t=><View key={t} style={s.tag}><Text style={s.tagText}>{t}</Text></View>)}</View></View>)}{!entries.length?<Text style={s.empty}>Aucune note pour le moment.</Text>:null}</ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},header:{paddingTop:54,paddingHorizontal:16,paddingBottom:10,flexDirection:'row',gap:10,alignItems:'center'},back:{width:38,height:38,borderRadius:13,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',...Shadow.sm},eyebrow:{fontSize:8.5,color:Colors.violet,fontWeight:FontWeight.extrabold,letterSpacing:1.2},title:{fontSize:21,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},wrap:{padding:Spacing.md,gap:10,paddingBottom:70},insight:{backgroundColor:'#F5F3FF',borderRadius:16,padding:12,flexDirection:'row',gap:8,alignItems:'center'},insightText:{flex:1,fontSize:10.5,color:Colors.textPrimary,lineHeight:15},composer:{backgroundColor:'#fff',borderRadius:18,padding:12,...Shadow.sm},input:{minHeight:100,textAlignVertical:'top',fontSize:11.5,color:Colors.textPrimary,lineHeight:17},add:{height:42,borderRadius:13,backgroundColor:Colors.electric,flexDirection:'row',gap:6,alignItems:'center',justifyContent:'center'},addText:{color:'#fff',fontSize:11,fontWeight:FontWeight.extrabold},section:{fontSize:14,fontWeight:FontWeight.extrabold,color:Colors.textPrimary,marginTop:5},entry:{backgroundColor:'#fff',borderRadius:17,padding:12},entryTop:{flexDirection:'row',alignItems:'center',gap:6},date:{fontSize:9,color:Colors.textTertiary},entryText:{fontSize:11,color:Colors.textPrimary,lineHeight:16,marginTop:7},tags:{flexDirection:'row',flexWrap:'wrap',gap:5,marginTop:8},tag:{backgroundColor:Colors.electricDim,borderRadius:99,paddingHorizontal:7,paddingVertical:4},tagText:{fontSize:8,color:Colors.electric,fontWeight:FontWeight.bold},empty:{fontSize:10,color:Colors.textTertiary,textAlign:'center',padding:20}})
