import React,{useMemo}from'react'
import{View,Text,StyleSheet,ScrollView,TouchableOpacity}from'react-native'
import{useSafeAreaInsets}from'react-native-safe-area-context'
import{router}from'expo-router'
import{ArrowLeft,HeartPulse,Moon,Droplets,Brain,Utensils,CalendarDays,ChevronRight}from'lucide-react-native'
import{LinearGradient}from'expo-linear-gradient'
import{useSession}from'@/hooks/useProfile';import{useActivities}from'@/hooks/useActivities';import{buildLifeSnapshot}from'@/lib/v11/life';import{Colors,Shadow}from'@/constants/theme'
export default function LifeHub(){const ins=useSafeAreaInsets(),{userId}=useSession(),{activities}=useActivities(userId??undefined,60);const life=useMemo(()=>buildLifeSnapshot(activities as any[]),[activities]);const items=[['Récupération & sommeil','Check-in, sommeil, douleurs et charge','/modals/recovery',Moon,'#4F46E5'],['Fuel & hydratation','Prépare avant / pendant / après','/modals/fuel',Utensils,'#F59E0B'],['Mental & focus','Respiration et routine de compétition','/modals/mind',Brain,'#EC4899'],['Mode compétition','Checklist, objectif et tracking','/modals/competition-mode',CalendarDays,'#10B981']] as const;return <View style={[s.root,{paddingTop:ins.top}]}><View style={s.header}><TouchableOpacity style={s.back} onPress={()=>router.back()}><ArrowLeft size={20} color={Colors.textPrimary}/></TouchableOpacity><View><Text style={s.title}>Hybrid Life</Text><Text style={s.sub}>Avant · pendant · après</Text></View></View><ScrollView contentContainerStyle={{padding:16,paddingBottom:40}}><LinearGradient colors={['#0B1220','#16223B']} style={s.hero}><Text style={s.kicker}>ÉTAT DU JOUR</Text><View style={s.heroRow}><Text style={[s.big,{color:life.trainingColor}]}>{life.score}</Text><View style={{flex:1}}><Text style={s.headline}>{life.headline}</Text><Text style={s.heroSub}>{life.actions[0]}</Text></View></View><View style={s.metrics}>{[['Récup',life.recovery],['Sommeil',life.sleep],['Hydra',life.hydration],['Mental',life.mind]].map(([l,v])=><View style={s.metric} key={String(l)}><Text style={s.mv}>{v}</Text><Text style={s.ml}>{l}</Text></View>)}</View></LinearGradient>{items.map(([t,d,r,I,c])=><TouchableOpacity key={t} style={s.card} onPress={()=>router.push(r as any)}><View style={[s.ico,{backgroundColor:c+'16'}]}><I size={21} color={c}/></View><View style={{flex:1}}><Text style={s.ct}>{t}</Text><Text style={s.cd}>{d}</Text></View><ChevronRight size={18} color="#94A3B8"/></TouchableOpacity>)}<View style={s.tip}><HeartPulse size={17} color="#7C3AED"/><Text style={s.tipText}>Hybrid Life guide l’entraînement à partir de tes données et sensations, mais ne remplace pas un professionnel de santé.</Text></View></ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},header:{height:68,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:11,backgroundColor:'#fff',borderBottomWidth:1,borderColor:Colors.borderLight},back:{width:38,height:38,borderRadius:13,backgroundColor:Colors.bgAlt,alignItems:'center',justifyContent:'center'},title:{fontSize:19,fontWeight:'900',color:Colors.textPrimary},sub:{fontSize:10.5,color:Colors.textTertiary},hero:{borderRadius:26,padding:18,...Shadow.md},kicker:{fontSize:9,color:'#94A3B8',fontWeight:'900',letterSpacing:1.3},heroRow:{flexDirection:'row',alignItems:'center',gap:16,marginTop:8},big:{fontSize:52,fontWeight:'900'},headline:{fontSize:17,fontWeight:'900',color:'#fff'},heroSub:{fontSize:10.5,color:'#CBD5E1',lineHeight:15,marginTop:4},metrics:{flexDirection:'row',gap:7,marginTop:14},metric:{flex:1,backgroundColor:'#18243A',borderRadius:13,padding:9,alignItems:'center'},mv:{fontSize:15,fontWeight:'900',color:'#fff'},ml:{fontSize:8,color:'#94A3B8'},card:{backgroundColor:'#fff',borderRadius:20,padding:15,marginTop:10,flexDirection:'row',alignItems:'center',gap:11,...Shadow.sm},ico:{width:44,height:44,borderRadius:15,alignItems:'center',justifyContent:'center'},ct:{fontSize:13.5,fontWeight:'900',color:Colors.textPrimary},cd:{fontSize:10,color:Colors.textSecondary,marginTop:2},tip:{marginTop:14,backgroundColor:'#F5F3FF',borderRadius:16,padding:13,flexDirection:'row',gap:9},tipText:{flex:1,fontSize:9.5,lineHeight:14,color:'#5B21B6'}})
