import React,{useMemo,useState}from'react'
import{View,Text,StyleSheet,TouchableOpacity,ScrollView}from'react-native'
import{useSafeAreaInsets}from'react-native-safe-area-context'
import{router}from'expo-router'
import{ArrowLeft,Moon,Activity,HeartPulse,Sparkles,Check}from'lucide-react-native'
import{LinearGradient}from'expo-linear-gradient'
import{Colors,FontWeight,Shadow}from'@/constants/theme'
import{useSession}from'@/hooks/useProfile'
import{supabase}from'@/lib/supabase'

export default function ReadinessScreen(){
 const insets=useSafeAreaInsets();const{userId}=useSession();const[sleep,setSleep]=useState(4),[fatigue,setFatigue]=useState(2),[soreness,setSoreness]=useState(2),[motivation,setMotivation]=useState(4),[saved,setSaved]=useState(false)
 const score=useMemo(()=>Math.max(0,Math.min(100,Math.round((sleep/5*30)+((6-fatigue)/5*25)+((6-soreness)/5*20)+(motivation/5*25)))),[sleep,fatigue,soreness,motivation])
 const save=async()=>{if(userId){await supabase.from('readiness_logs').upsert({user_id:userId,log_date:new Date().toISOString().slice(0,10),sleep_quality:sleep,fatigue,soreness,motivation,score} as any,{onConflict:'user_id,log_date'})}setSaved(true);setTimeout(()=>router.back(),450)}
 const color=score>=80?'#10B981':score>=60?'#F59E0B':'#EF4444'; const label=score>=80?'Très prêt':score>=60?'Correct':'Récupération'
 return <View style={[s.root,{paddingTop:insets.top}]}><View style={s.header}><TouchableOpacity style={s.back} onPress={()=>router.back()}><ArrowLeft size={20} color={Colors.textPrimary}/></TouchableOpacity><View><Text style={s.title}>Check-in récupération</Text><Text style={s.sub}>20 secondes pour adapter ta journée</Text></View></View><ScrollView contentContainerStyle={{paddingBottom:40}}>
  <LinearGradient colors={['#0F1C3D','#172554']} style={s.hero}><Sparkles size={22} color="#A5B4FC"/><Text style={s.score}>{score}</Text><Text style={[s.label,{color}]}>{label}</Text><Text style={s.heroSub}>Ce score mélange ton ressenti du jour. Les données de montre pourront compléter ce check-in.</Text></LinearGradient>
  <Question icon={<Moon size={19} color="#6366F1"/>} title="Qualité du sommeil" value={sleep} onChange={setSleep} low="Très mauvaise" high="Excellente" invert={false}/>
  <Question icon={<Activity size={19} color="#F59E0B"/>} title="Fatigue générale" value={fatigue} onChange={setFatigue} low="Très faible" high="Très forte" invert/>
  <Question icon={<HeartPulse size={19} color="#EF4444"/>} title="Douleurs / courbatures" value={soreness} onChange={setSoreness} low="Aucune" high="Fortes" invert/>
  <Question icon={<Sparkles size={19} color="#8B5CF6"/>} title="Motivation" value={motivation} onChange={setMotivation} low="Aucune" high="Très élevée" invert={false}/>
  <TouchableOpacity style={[s.save,saved&&{backgroundColor:'#10B981'}]} onPress={save}>{saved?<Check size={20} color="#fff"/>:null}<Text style={s.saveText}>{saved?'Enregistré':'Enregistrer mon check-in'}</Text></TouchableOpacity>
 </ScrollView></View>
}
function Question({icon,title,value,onChange,low,high}:{icon:React.ReactNode;title:string;value:number;onChange:(v:number)=>void;low:string;high:string;invert?:boolean}){return <View style={s.card}><View style={s.qTop}>{icon}<Text style={s.qTitle}>{title}</Text><Text style={s.qValue}>{value}/5</Text></View><View style={s.scale}>{[1,2,3,4,5].map(v=><TouchableOpacity key={v} style={[s.scaleBtn,value===v&&s.scaleActive]} onPress={()=>onChange(v)}><Text style={[s.scaleText,value===v&&s.scaleTextActive]}>{v}</Text></TouchableOpacity>)}</View><View style={s.ends}><Text style={s.endText}>{low}</Text><Text style={s.endText}>{high}</Text></View></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},header:{height:68,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:11,backgroundColor:'#fff',borderBottomWidth:1,borderColor:Colors.borderLight},back:{width:38,height:38,borderRadius:13,backgroundColor:Colors.bgAlt,alignItems:'center',justifyContent:'center'},title:{fontSize:19,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},sub:{fontSize:10.5,color:Colors.textTertiary,marginTop:1},hero:{margin:16,borderRadius:25,padding:20,alignItems:'center',...Shadow.md},score:{fontSize:52,fontWeight:FontWeight.extrabold,color:'#fff',lineHeight:60,marginTop:3},label:{fontSize:13,fontWeight:FontWeight.extrabold},heroSub:{fontSize:10.5,color:'#C7D2FE',textAlign:'center',lineHeight:15,marginTop:8,maxWidth:280},card:{marginHorizontal:16,marginBottom:10,backgroundColor:'#fff',borderRadius:20,padding:15,...Shadow.sm},qTop:{flexDirection:'row',alignItems:'center',gap:9},qTitle:{flex:1,fontSize:12.5,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},qValue:{fontSize:11,color:Colors.textSecondary,fontWeight:FontWeight.bold},scale:{flexDirection:'row',gap:8,marginTop:14},scaleBtn:{flex:1,height:40,borderRadius:12,backgroundColor:Colors.bg,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:Colors.borderLight},scaleActive:{backgroundColor:Colors.electric,borderColor:Colors.electric},scaleText:{fontWeight:FontWeight.bold,color:Colors.textSecondary},scaleTextActive:{color:'#fff'},ends:{flexDirection:'row',justifyContent:'space-between',marginTop:6},endText:{fontSize:8.5,color:Colors.textTertiary},save:{margin:16,backgroundColor:Colors.textPrimary,borderRadius:17,paddingVertical:15,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},saveText:{color:'#fff',fontWeight:FontWeight.extrabold}})
