import React,{useMemo}from'react'
import{View,Text,StyleSheet,ScrollView}from'react-native'
import{router}from'expo-router'
import{ChevronLeft,Sparkles,Clock,Flame,Trophy,Share2}from'lucide-react-native'
import{useActivities}from'@/hooks/useActivities'
import{useSession}from'@/hooks/useProfile'
import{SPORT_BY_KEY}from'@/constants/sportCatalog'
import{buildHybridIntelligence}from'@/lib/v10/intelligence'
import{SensoryPressable}from'@/components/v6/SensoryPressable'
import{Colors,Shadow}from'@/constants/theme'
export default function Recap(){const{userId}=useSession();const{activities}=useActivities(userId??undefined,31);const intel=useMemo(()=>buildHybridIntelligence(activities),[activities]);const totalMin=Math.round(activities.reduce((s,a)=>s+a.duration_seconds/60,0));const sports=new Map<string,number>();activities.forEach(a=>sports.set(a.sport_type,(sports.get(a.sport_type)||0)+a.duration_seconds));const top=[...sports.entries()].sort((a,b)=>b[1]-a[1])[0];const verified=activities.filter(a=>a.is_verified).length;return <View style={s.root}><View style={s.header}><SensoryPressable event="tap" onPress={()=>router.back()} style={s.back}><ChevronLeft size={21}/></SensoryPressable><View><Text style={s.kicker}>HYBRID RECAP</Text><Text style={s.h1}>Tes 30 derniers jours</Text></View></View><ScrollView contentContainerStyle={s.content}><View style={s.hero}><Sparkles size={30} color="#C4B5FD"/><Text style={s.big}>{activities.length}</Text><Text style={s.bigLabel}>séances enregistrées</Text><Text style={s.summary}>Tu es actuellement en phase <Text style={{fontWeight:'900',color:'#fff'}}>{intel.state.toUpperCase()}</Text>. Ton score de forme est à {intel.form}/100.</Text></View><View style={s.grid}><Stat icon={<Clock size={18} color="#2563EB"/>} value={`${Math.floor(totalMin/60)}h ${totalMin%60}m`} label="Temps sportif"/><Stat icon={<Flame size={18} color="#F97316"/>} value={`${intel.consistency}/100`} label="Régularité"/><Stat icon={<Trophy size={18} color="#D97706"/>} value={top?SPORT_BY_KEY[top[0]]?.label??top[0]:'—'} label="Sport dominant"/><Stat icon={<Sparkles size={18} color="#7C3AED"/>} value={`${verified}/${activities.length}`} label="Activités vérifiées"/></View><Text style={s.section}>LE MOMENT CLÉ</Text><View style={s.card}><Text style={s.cardTitle}>{intel.progression>=60?'Tu progresses.':'Tu consolides.'}</Text><Text style={s.body}>{intel.recommendations[0]}</Text></View><Text style={s.section}>À RETENIR</Text>{intel.strengths.length?intel.strengths.map(x=><View style={s.line} key={x}><View style={s.bullet}/><Text style={s.lineText}>{x}</Text></View>):<Text style={s.body}>Continue à enregistrer tes séances pour enrichir le résumé.</Text>}<SensoryPressable event="success" onPress={()=>{}} style={s.share}><Share2 size={18} color="#fff"/><Text style={s.shareText}>Préparer une carte partageable</Text></SensoryPressable></ScrollView></View>}
function Stat({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <View style={s.stat}>{icon}<Text numberOfLines={1} style={s.value}>{value}</Text><Text style={s.label}>{label}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#F4F7FB'},header:{paddingTop:56,paddingHorizontal:16,paddingBottom:12,flexDirection:'row',gap:10,alignItems:'center'},back:{width:38,height:38,borderRadius:13,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',...Shadow.sm},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:'#7C3AED'},h1:{fontSize:24,fontWeight:'900',color:Colors.textPrimary},content:{padding:16,paddingBottom:44},hero:{backgroundColor:'#312E81',borderRadius:27,padding:22,alignItems:'center',...Shadow.md},big:{fontSize:46,fontWeight:'900',color:'#fff',marginTop:5},bigLabel:{fontSize:11,color:'#C4B5FD',fontWeight:'800'},summary:{fontSize:12,lineHeight:18,color:'#DDD6FE',textAlign:'center',marginTop:14},grid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:10},stat:{width:'48.7%',backgroundColor:'#fff',borderRadius:18,padding:14,...Shadow.sm},value:{fontSize:17,fontWeight:'900',color:Colors.textPrimary,marginTop:7},label:{fontSize:9.5,color:Colors.textTertiary,marginTop:2},section:{fontSize:10,fontWeight:'900',letterSpacing:1.1,color:Colors.textTertiary,marginTop:20,marginBottom:8},card:{backgroundColor:'#fff',borderRadius:18,padding:14,...Shadow.sm},cardTitle:{fontSize:14,fontWeight:'900',color:Colors.textPrimary},body:{fontSize:11,lineHeight:17,color:Colors.textSecondary,marginTop:5},line:{flexDirection:'row',alignItems:'center',gap:8,backgroundColor:'#fff',borderRadius:14,padding:11,marginBottom:6},bullet:{width:7,height:7,borderRadius:4,backgroundColor:'#10B981'},lineText:{fontSize:11.5,color:Colors.textPrimary,fontWeight:'700'},share:{marginTop:20,borderRadius:16,backgroundColor:'#0B1220',padding:14,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:8},shareText:{color:'#fff',fontWeight:'900',fontSize:12}})
