import React, { useMemo } from 'react'
import { View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import { router } from 'expo-router'
import { ArrowLeft, Trophy, Medal, Zap, Route, Timer, Dumbbell, Flame, Crown } from 'lucide-react-native'
import { LinearGradient } from 'expo-linear-gradient'
import { Colors, FontWeight, Shadow, SportColors } from '@/constants/theme'
import { useSession } from '@/hooks/useProfile'
import { useActivities } from '@/hooks/useActivities'
import type { Activity } from '@/types/database'

export default function RecordsScreen(){
 const insets=useSafeAreaInsets(); const {userId}=useSession(); const {activities}=useActivities(userId??undefined,3650)
 const r=useMemo(()=>computeRecords(activities as Activity[]),[activities])
 return <View style={[s.root,{paddingTop:insets.top}]}><View style={s.header}><TouchableOpacity style={s.back} onPress={()=>router.back()}><ArrowLeft size={20} color={Colors.textPrimary}/></TouchableOpacity><View><Text style={s.title}>Record Book</Text><Text style={s.sub}>Tous tes meilleurs accomplissements</Text></View></View><ScrollView contentContainerStyle={{paddingBottom:40}} showsVerticalScrollIndicator={false}>
   <LinearGradient colors={['#171A3A','#4C1D95','#7C3AED']} style={s.hero}><View style={s.crown}><Crown size={28} color="#FBBF24"/></View><Text style={s.heroEyebrow}>PERSONAL BESTS</Text><Text style={s.heroBig}>{r.total}</Text><Text style={s.heroSub}>records détectés dans ton historique</Text></LinearGradient>
   <Text style={s.section}>Endurance</Text><View style={s.grid}><Record icon={<Route size={20} color="#FF6B35"/>} tint="#FFF0E8" title="Plus longue distance" value={r.maxDistance?`${r.maxDistance.toFixed(1)} km`:'—'}/><Record icon={<Timer size={20} color="#1587FF"/>} tint="#EAF4FF" title="Plus longue séance" value={r.maxDuration?`${Math.round(r.maxDuration/60)} min`:'—'}/></View>
   <Text style={s.section}>Force & volume</Text><View style={s.grid}><Record icon={<Dumbbell size={20} color="#EF4444"/>} tint="#FEECEC" title="Charge max" value={r.maxWeight?`${r.maxWeight} kg`:'—'}/><Record icon={<Zap size={20} color="#8B5CF6"/>} tint="#F2EAFE" title="Volume max séance" value={r.maxVolume?`${Math.round(r.maxVolume)} kg`:'—'}/></View>
   <Text style={s.section}>Régularité</Text><View style={s.grid}><Record icon={<Flame size={20} color="#F59E0B"/>} tint="#FFF7E7" title="Série active" value={`${r.streak} j`}/><Record icon={<Trophy size={20} color="#10B981"/>} tint="#E9FBF2" title="Sports pratiqués" value={`${r.sports}`}/></View>
   <Text style={s.section}>Moments marquants</Text>{r.highlights.map((h,i)=><View key={i} style={s.highlight}><View style={[s.medal,{backgroundColor:(SportColors[h.sport]??Colors.electric)+'18'}]}><Medal size={19} color={SportColors[h.sport]??Colors.electric}/></View><View style={{flex:1}}><Text style={s.highlightTitle}>{h.title}</Text><Text style={s.highlightSub}>{new Date(h.date).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</Text></View><Text style={s.highlightValue}>{h.value}</Text></View>)}
 </ScrollView></View>
}
function computeRecords(acts:Activity[]){let maxDistance=0,maxDuration=0,maxWeight=0,maxVolume=0; const sports=new Set<string>(); const highlights:any[]=[]; const days=new Set<string>(); for(const a of acts){sports.add(a.sport_type);days.add((a.performed_at??a.created_at).slice(0,10)); const d=Number(a.metrics?.distance_km??a.metrics?.distance??0); if(d>maxDistance){maxDistance=d;highlights.unshift({sport:a.sport_type,title:'Nouvelle plus longue distance',value:`${d.toFixed(1)} km`,date:a.performed_at})} maxDuration=Math.max(maxDuration,a.duration_seconds||0); for(const ex of (a.metrics?.exercises??[])){let vol=0;for(const st of (ex.sets??[])){maxWeight=Math.max(maxWeight,Number(st.weight_kg??0));vol+=Number(st.weight_kg??0)*Number(st.reps??0)}maxVolume=Math.max(maxVolume,vol)}} let streak=0; const cur=new Date(); for(let i=0;i<365;i++){const k=cur.toISOString().slice(0,10);if(days.has(k)){streak++;cur.setDate(cur.getDate()-1)}else if(i===0){cur.setDate(cur.getDate()-1)}else break} return{maxDistance,maxDuration,maxWeight,maxVolume,sports:sports.size,streak,total:[maxDistance,maxDuration,maxWeight,maxVolume,streak,sports.size].filter(Boolean).length,highlights:highlights.slice(0,5)}}
function Record({icon,tint,title,value}:{icon:React.ReactNode;tint:string;title:string;value:string}){return <View style={s.record}><View style={[s.icon,{backgroundColor:tint}]}>{icon}</View><Text style={s.recordTitle}>{title}</Text><Text style={s.recordValue}>{value}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},header:{height:68,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:11,backgroundColor:'#fff',borderBottomWidth:1,borderColor:Colors.borderLight},back:{width:38,height:38,borderRadius:13,backgroundColor:Colors.bgAlt,alignItems:'center',justifyContent:'center'},title:{fontSize:19,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},sub:{fontSize:10.5,color:Colors.textTertiary,marginTop:1},hero:{margin:16,borderRadius:26,padding:20,alignItems:'center',...Shadow.lg},crown:{width:54,height:54,borderRadius:18,backgroundColor:'rgba(255,255,255,.10)',alignItems:'center',justifyContent:'center'},heroEyebrow:{fontSize:9,color:'#C4B5FD',fontWeight:FontWeight.extrabold,letterSpacing:1.4,marginTop:10},heroBig:{fontSize:48,color:'#fff',fontWeight:FontWeight.extrabold,lineHeight:55},heroSub:{fontSize:11,color:'#DDD6FE'},section:{marginHorizontal:16,marginTop:8,marginBottom:9,fontSize:13,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},grid:{flexDirection:'row',gap:10,paddingHorizontal:16,marginBottom:13},record:{flex:1,backgroundColor:'#fff',borderRadius:19,padding:14,...Shadow.sm},icon:{width:38,height:38,borderRadius:12,alignItems:'center',justifyContent:'center'},recordTitle:{fontSize:10.5,color:Colors.textSecondary,marginTop:10},recordValue:{fontSize:20,fontWeight:FontWeight.extrabold,color:Colors.textPrimary,marginTop:3},highlight:{marginHorizontal:16,marginBottom:8,backgroundColor:'#fff',borderRadius:17,padding:12,flexDirection:'row',alignItems:'center',gap:10,...Shadow.sm},medal:{width:38,height:38,borderRadius:12,alignItems:'center',justifyContent:'center'},highlightTitle:{fontSize:11.5,fontWeight:FontWeight.bold,color:Colors.textPrimary},highlightSub:{fontSize:9.5,color:Colors.textTertiary,marginTop:2},highlightValue:{fontSize:12,fontWeight:FontWeight.extrabold,color:Colors.electric}})
