import React,{useState}from'react'
import{View,Text,StyleSheet,ScrollView}from'react-native'
import{router}from'expo-router'
import{ChevronLeft,FlaskConical,ArrowRight}from'lucide-react-native'
import{Colors,FontWeight,Shadow,Spacing}from'@/constants/theme'
import{useSession,useProfile}from'@/hooks/useProfile';import{useActivities}from'@/hooks/useActivities';import{useLifeCheckin}from'@/hooks/useLifeCheckin';import{useAdaptiveOS}from'@/hooks/v12/useAdaptiveOS';import{simulateScenario}from'@/lib/v12/adaptive';import{SensoryPressable}from'@/components/v6/SensoryPressable'
type S='more_volume'|'miss_session'|'competition'|'poor_sleep';const options:[S,string,string][]=[['more_volume','+25 % de volume','Que se passe-t-il si j’augmente beaucoup ?'],['miss_session','Je rate une séance','Est-ce que je dois la rattraper ?'],['competition','Compétition surprise','Comment réorganiser la semaine ?'],['poor_sleep','Mauvaise nuit','Faut-il maintenir l’intensité ?']]
export default function ScenarioLab(){const{userId}=useSession();const{profile}=useProfile(userId??undefined);const{activities}=useActivities(userId??undefined,3650);const{checkin}=useLifeCheckin(userId??undefined);const{snapshot}=useAdaptiveOS(activities,profile?.favorite_sports??[],checkin);const[selected,setSelected]=useState<S>('more_volume');const r=simulateScenario(snapshot,selected);return <View style={s.root}><View style={s.header}><SensoryPressable onPress={()=>router.back()} style={s.back}><ChevronLeft size={21}/></SensoryPressable><View><Text style={s.eyebrow}>WHAT IF?</Text><Text style={s.title}>Scenario Lab</Text></View></View><ScrollView contentContainerStyle={s.wrap}><View style={s.hero}><FlaskConical size={25} color="#fff"/><Text style={s.heroTitle}>Teste avant de modifier ton plan.</Text><Text style={s.heroText}>Hybrid simule l’impact organisationnel et de charge. Ce n’est pas une prédiction médicale.</Text></View><View style={s.options}>{options.map(([key,title,sub])=><SensoryPressable key={key} onPress={()=>setSelected(key)} style={[s.option,selected===key&&s.optionOn]} event="selection"><Text style={[s.optionTitle,selected===key&&{color:Colors.electric}]}>{title}</Text><Text style={s.optionSub}>{sub}</Text></SensoryPressable>)}</View><View style={s.result}><Text style={s.resultEyebrow}>SIMULATION</Text><Text style={s.resultTitle}>{r.title}</Text><Row label="Effet probable" value={r.effect}/><Row label="Point d’attention" value={r.risk}/><View style={s.rec}><Text style={s.recLabel}>RECOMMANDATION</Text><Text style={s.recText}>{r.recommendation}</Text></View></View><SensoryPressable onPress={()=>router.push('/modals/adaptive-plan' as any)} style={s.cta}><Text style={s.ctaText}>Retour au plan adaptatif</Text><ArrowRight size={16} color="#fff"/></SensoryPressable></ScrollView></View>}
function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.rowLabel}>{label}</Text><Text style={s.rowValue}>{value}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},header:{paddingTop:54,paddingHorizontal:16,paddingBottom:10,flexDirection:'row',gap:10,alignItems:'center'},back:{width:38,height:38,borderRadius:13,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',...Shadow.sm},eyebrow:{fontSize:8.5,color:Colors.violet,fontWeight:FontWeight.extrabold,letterSpacing:1.2},title:{fontSize:21,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},wrap:{padding:Spacing.md,gap:10,paddingBottom:70},hero:{backgroundColor:'#172554',borderRadius:23,padding:16,gap:7},heroTitle:{fontSize:17,color:'#fff',fontWeight:FontWeight.extrabold},heroText:{fontSize:10.5,color:'#C7D2FE',lineHeight:15},options:{flexDirection:'row',flexWrap:'wrap',gap:8},option:{width:'48.5%',backgroundColor:'#fff',borderWidth:1,borderColor:Colors.border,borderRadius:16,padding:11},optionOn:{borderColor:Colors.electric,backgroundColor:Colors.electricDim},optionTitle:{fontSize:11,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},optionSub:{fontSize:9,color:Colors.textTertiary,lineHeight:13,marginTop:3},result:{backgroundColor:'#fff',borderRadius:20,padding:15,...Shadow.sm},resultEyebrow:{fontSize:8,color:Colors.violet,fontWeight:FontWeight.extrabold,letterSpacing:1.1},resultTitle:{fontSize:18,fontWeight:FontWeight.extrabold,color:Colors.textPrimary,marginTop:3,marginBottom:8},row:{borderTopWidth:1,borderTopColor:Colors.borderLight,paddingVertical:9},rowLabel:{fontSize:8.5,color:Colors.textTertiary,fontWeight:FontWeight.bold},rowValue:{fontSize:11,color:Colors.textPrimary,fontWeight:FontWeight.semibold,marginTop:3},rec:{backgroundColor:'#F5F3FF',borderRadius:14,padding:11,marginTop:4},recLabel:{fontSize:8,color:Colors.violet,fontWeight:FontWeight.extrabold},recText:{fontSize:11,color:Colors.textPrimary,lineHeight:16,marginTop:3},cta:{height:46,borderRadius:15,backgroundColor:Colors.textPrimary,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},ctaText:{color:'#fff',fontSize:11,fontWeight:FontWeight.extrabold}})
