import React from'react'
import{View,Text,StyleSheet,ScrollView}from'react-native'
import{LinearGradient}from'expo-linear-gradient'
import{router}from'expo-router'
import{ChevronLeft,Lock,Check,Crown,Sparkles}from'lucide-react-native'
import{SensoryPressable}from'@/components/v6/SensoryPressable'
import{V8_SEASON}from'@/constants/v8'
import{useV7Economy}from'@/hooks/v7/useV7Economy'
import{Colors,FontWeight,Shadow}from'@/constants/theme'
export default function SeasonScreen(){const{state,level}=useV7Economy();const xp=state.xp;const active=[...V8_SEASON.tiers].reverse().find(t=>xp>=t.xp)??V8_SEASON.tiers[0];const pct=Math.min(100,Math.round((xp/(V8_SEASON.tiers.at(-1)?.xp??1))*100));return <View style={s.root}><LinearGradient colors={['#120029','#3B0764','#7C3AED']} style={s.hero}><View style={s.nav}><SensoryPressable event="selection" onPress={()=>router.back()} style={s.back}><ChevronLeft size={21} color="#fff"/></SensoryPressable><View><Text style={s.kicker}>SEASON 08</Text><Text style={s.h1}>{V8_SEASON.name}</Text></View><Crown size={22} color="#FBBF24"/></View><Text style={s.subtitle}>{V8_SEASON.subtitle}</Text><View style={s.progress}><View style={[s.fill,{width:`${pct}%`}]}/></View><View style={s.progressMeta}><Text style={s.progressText}>{xp.toLocaleString()} XP</Text><Text style={s.progressText}>{pct}%</Text></View></LinearGradient><ScrollView contentContainerStyle={s.body}><View style={s.banner}><Sparkles size={18} color="#7C3AED"/><View style={{flex:1}}><Text style={s.bannerTitle}>Une saison sans pay-to-win</Text><Text style={s.bannerText}>Les récompenses sont cosmétiques, sociales ou de progression. Les temps, records et classements officiels restent intacts.</Text></View></View><Text style={s.section}>Parcours de saison</Text>{V8_SEASON.tiers.map((t,i)=>{const done=xp>=t.xp,current=t.tier===active.tier;return <View key={t.tier} style={[s.tier,current&&s.tierCurrent]}><View style={[s.badge,done&&s.badgeDone]}>{done?<Check size={15} color="#fff"/>:<Lock size={13} color="#94A3B8"/>}</View><View style={{flex:1}}><Text style={s.tierTitle}>Palier {t.tier}</Text><Text style={s.reward}>{t.reward}</Text></View><Text style={s.xp}>{t.xp.toLocaleString()} XP</Text></View>})}<View style={s.event}><Text style={s.eventKicker}>ÉVÉNEMENT MONDIAL</Text><Text style={s.eventTitle}>October Movement</Text><Text style={s.eventText}>Chaque discipline contribue au compteur collectif. Running, boxe, natation, muscu, sports de raquette : l’effort est converti en Effort Units pour que chacun participe de manière équitable.</Text><View style={s.communityTrack}><View style={s.communityFill}/></View><Text style={s.communityText}>Objectif communautaire · prototype V8</Text></View></ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},hero:{paddingTop:54,paddingHorizontal:18,paddingBottom:22},nav:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:40,height:40,borderRadius:14,backgroundColor:'rgba(255,255,255,.1)',alignItems:'center',justifyContent:'center'},kicker:{fontSize:8,color:'#C4B5FD',fontWeight:FontWeight.extrabold,letterSpacing:1.4,textAlign:'center'},h1:{fontSize:22,color:'#fff',fontWeight:FontWeight.extrabold,textAlign:'center'},subtitle:{fontSize:11,color:'#DDD6FE',fontWeight:FontWeight.bold,textAlign:'center',marginTop:14},progress:{height:9,borderRadius:99,backgroundColor:'rgba(255,255,255,.14)',marginTop:15,overflow:'hidden'},fill:{height:'100%',borderRadius:99,backgroundColor:'#FBBF24'},progressMeta:{flexDirection:'row',justifyContent:'space-between',marginTop:6},progressText:{fontSize:9,color:'#EDE9FE',fontWeight:FontWeight.extrabold},body:{padding:16,paddingBottom:50},banner:{flexDirection:'row',gap:10,padding:14,borderRadius:18,backgroundColor:'#F5F3FF'},bannerTitle:{fontSize:11,color:'#5B21B6',fontWeight:FontWeight.extrabold},bannerText:{fontSize:9,lineHeight:14,color:'#7C3AED',marginTop:3},section:{fontSize:14,color:Colors.textPrimary,fontWeight:FontWeight.extrabold,marginTop:18,marginBottom:10},tier:{flexDirection:'row',alignItems:'center',gap:11,padding:13,backgroundColor:Colors.bgCard,borderRadius:17,borderWidth:1,borderColor:Colors.borderLight,marginBottom:8,...Shadow.sm},tierCurrent:{borderColor:'#A78BFA',backgroundColor:'#FAF5FF'},badge:{width:32,height:32,borderRadius:16,backgroundColor:'#E2E8F0',alignItems:'center',justifyContent:'center'},badgeDone:{backgroundColor:'#7C3AED'},tierTitle:{fontSize:11,color:Colors.textPrimary,fontWeight:FontWeight.extrabold},reward:{fontSize:9,color:Colors.textSecondary,marginTop:2},xp:{fontSize:9,color:'#7C3AED',fontWeight:FontWeight.extrabold},event:{marginTop:16,borderRadius:22,padding:17,backgroundColor:'#07111F'},eventKicker:{fontSize:8,color:'#67E8F9',fontWeight:FontWeight.extrabold,letterSpacing:1.3},eventTitle:{fontSize:20,color:'#fff',fontWeight:FontWeight.extrabold,marginTop:5},eventText:{fontSize:10,lineHeight:16,color:'#CBD5E1',marginTop:7},communityTrack:{height:8,borderRadius:99,backgroundColor:'rgba(255,255,255,.1)',marginTop:15,overflow:'hidden'},communityFill:{width:'62%',height:'100%',backgroundColor:'#22D3EE',borderRadius:99},communityText:{fontSize:8,color:'#94A3B8',fontWeight:FontWeight.bold,marginTop:6}})
