import React,{useState}from'react'
import{SafeAreaView,View,Text,StyleSheet,Switch}from'react-native'
import{router}from'expo-router'
import{ChevronLeft,Volume2,Vibrate,Sparkles,Play,ShieldCheck}from'lucide-react-native'
import{Colors,FontWeight,Shadow,Spacing}from'@/constants/theme'
import{useSensoryPreferences}from'@/hooks/useSensoryPreferences'
import{useSensoryFeedback}from'@/hooks/useSensoryFeedback'
import{SensoryPressable}from'@/components/v6/SensoryPressable'
import{RewardBurst}from'@/components/v5/RewardBurst'
export default function SensorySettings(){const{prefs,update}=useSensoryPreferences();const{play}=useSensoryFeedback();const[demo,setDemo]=useState(false);return <SafeAreaView style={s.safe}><View style={s.head}><SensoryPressable event="selection" style={s.back} onPress={()=>router.back()}><ChevronLeft size={21} color={Colors.textPrimary}/></SensoryPressable><View><Text style={s.title}>Sensations</Text><Text style={s.sub}>Le feeling de Hybrid, sous ton contrôle</Text></View></View><View style={s.content}><Row icon={<Vibrate size={20} color="#7C3AED"/>} title="Vibrations haptiques" sub="Feedback léger sur boutons, navigation, erreurs et réussites" value={prefs.haptics} onValueChange={v=>{update({haptics:v});if(v)setTimeout(()=>play('success'),80)}}/><Row icon={<Volume2 size={20} color="#315CFF"/>} title="Effets sonores" sub="Sons courts uniquement aux moments importants" value={prefs.sounds} onValueChange={v=>{update({sounds:v});if(v)setTimeout(()=>play('success'),80)}}/><Row icon={<Sparkles size={20} color="#F59E0B"/>} title="Réduire les animations" sub="Désactive les mouvements décoratifs et raccourcit les transitions" value={prefs.reducedMotion} onValueChange={v=>update({reducedMotion:v})}/><View style={s.preview}><View style={s.previewIcon}><ShieldCheck size={22} color="#10B981"/></View><View style={{flex:1}}><Text style={s.previewTitle}>Teste le feeling V6</Text><Text style={s.previewSub}>Aperçu d’une vraie récompense, sans modifier ton XP.</Text></View><SensoryPressable event="selection" style={s.previewBtn} onPress={()=>setDemo(true)}><Play size={14} color="#fff" fill="#fff"/><Text style={s.previewBtnText}>Tester</Text></SensoryPressable></View><View style={s.tip}><Text style={s.tipTitle}>Satisfaisant, jamais envahissant.</Text><Text style={s.tipText}>Hybrid célèbre les actions sportives réelles. Les interactions ordinaires restent silencieuses ou très discrètes, et tout peut être désactivé.</Text></View></View><RewardBurst visible={demo} title="Nouveau record" subtitle="10 km · 41:24 · -38 s" xp={120} onClose={()=>setDemo(false)}/></SafeAreaView>}
function Row({icon,title,sub,value,onValueChange}:any){return <View style={s.row}><View style={s.icon}>{icon}</View><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowSub}>{sub}</Text></View><Switch value={value} onValueChange={onValueChange} trackColor={{true:'#A5B4FC',false:'#DCE5F0'}} thumbColor={value?'#315CFF':'#fff'}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.bg},head:{flexDirection:'row',alignItems:'center',gap:12,padding:Spacing.md},back:{width:40,height:40,borderRadius:13,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',...Shadow.sm},title:{fontSize:21,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},sub:{fontSize:10.5,color:Colors.textTertiary},content:{padding:Spacing.md,gap:10},row:{backgroundColor:'#fff',borderRadius:18,padding:14,flexDirection:'row',gap:12,alignItems:'center',...Shadow.sm},icon:{width:42,height:42,borderRadius:14,backgroundColor:'#F5F7FB',alignItems:'center',justifyContent:'center'},rowTitle:{fontSize:13,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},rowSub:{fontSize:9.5,color:Colors.textSecondary,lineHeight:14,marginTop:3},preview:{backgroundColor:'#fff',borderRadius:20,padding:14,flexDirection:'row',alignItems:'center',gap:11,...Shadow.sm},previewIcon:{width:44,height:44,borderRadius:14,backgroundColor:'#E9FBF2',alignItems:'center',justifyContent:'center'},previewTitle:{fontSize:12.5,color:Colors.textPrimary,fontWeight:FontWeight.extrabold},previewSub:{fontSize:9.5,color:Colors.textSecondary,lineHeight:14,marginTop:2},previewBtn:{backgroundColor:Colors.textPrimary,borderRadius:12,paddingHorizontal:12,paddingVertical:9,flexDirection:'row',gap:5,alignItems:'center'},previewBtnText:{fontSize:9.5,color:'#fff',fontWeight:FontWeight.extrabold},tip:{backgroundColor:'#EEF2FF',borderRadius:18,padding:15,marginTop:8},tipTitle:{fontSize:12,fontWeight:FontWeight.extrabold,color:'#3730A3'},tipText:{fontSize:10,color:'#4F46E5',lineHeight:15,marginTop:4}})
