import React,{useEffect,useState}from'react'
import{View,Text,ScrollView,TouchableOpacity,StyleSheet,ActivityIndicator}from'react-native'
import{router}from'expo-router'
import{X}from'lucide-react-native'
import{Colors,FontSize,FontWeight,Radius,Spacing}from'@/constants/theme'
import{SportPicker}from'@/components/sports/SportPicker'
import{useProfile,useSession}from'@/hooks/useProfile'
import type{SportType}from'@/types/database'
export default function SportsModal(){const{userId}=useSession();const{profile,updateProfile}=useProfile(userId??undefined);const[selected,setSelected]=useState<SportType[]>([]);const[saving,setSaving]=useState(false);useEffect(()=>setSelected(profile?.favorite_sports??[]),[profile?.favorite_sports]);const save=async()=>{if(!selected.length)return;setSaving(true);try{await updateProfile({favorite_sports:selected});router.back()}finally{setSaving(false)}};return <View style={s.root}><View style={s.head}><View><Text style={s.title}>Mes sports</Text><Text style={s.sub}>Ajoute ou retire des disciplines à tout moment.</Text></View><TouchableOpacity onPress={()=>router.back()}><X size={22} color={Colors.textPrimary}/></TouchableOpacity></View><ScrollView contentContainerStyle={s.body}><SportPicker value={selected} onChange={setSelected}/></ScrollView><View style={s.foot}><TouchableOpacity onPress={save} disabled={saving||!selected.length} style={[s.save,(!selected.length||saving)&&{opacity:.55}]}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.saveText}>Enregistrer {selected.length} sport{selected.length>1?'s':''}</Text>}</TouchableOpacity></View></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},head:{padding:Spacing.lg,paddingTop:Spacing.xl,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',borderBottomWidth:1,borderColor:Colors.border},title:{fontSize:FontSize.xl,fontWeight:FontWeight.extrabold,color:Colors.textPrimary},sub:{fontSize:FontSize.sm,color:Colors.textSecondary,marginTop:4},body:{padding:Spacing.lg,paddingBottom:120},foot:{position:'absolute',left:0,right:0,bottom:0,padding:Spacing.md,backgroundColor:Colors.bgCard,borderTopWidth:1,borderColor:Colors.border},save:{backgroundColor:Colors.electric,borderRadius:Radius.md,padding:15,alignItems:'center'},saveText:{color:'#fff',fontWeight:FontWeight.bold,fontSize:FontSize.md}})
