import React,{useMemo}from'react'
import{View,Text,StyleSheet,ScrollView}from'react-native'
import{router}from'expo-router'
import{ChevronLeft,Flag,Trophy,Flame,ShieldCheck}from'lucide-react-native'
import{useActivities}from'@/hooks/useActivities'
import{useSession}from'@/hooks/useProfile'
import{SPORT_BY_KEY}from'@/constants/sportCatalog'
import{evaluateActivityIntegrity}from'@/lib/v10/integrity'
import{SensoryPressable}from'@/components/v6/SensoryPressable'
import{Colors,Shadow}from'@/constants/theme'
export default function Timeline(){const{userId}=useSession();const{activities}=useActivities(userId??undefined,3650);const moments=useMemo(()=>{const sorted=[...activities].sort((a,b)=>new Date(a.performed_at).getTime()-new Date(b.performed_at).getTime());let maxDist=0,maxDur=0;const out:any[]=[];sorted.forEach(a=>{const km=Number(a.metrics?.distance_km??0);const integ=evaluateActivityIntegrity(a);if(km>maxDist&&km>=5){maxDist=km;out.push({id:a.id+'d',date:a.performed_at,title:`Nouveau record de distance · ${km.toFixed(1)} km`,sub:SPORT_BY_KEY[a.sport_type]?.label??a.sport_type,verified:integ.status==='verified'})}if(a.duration_seconds>maxDur&&a.duration_seconds>=3600){maxDur=a.duration_seconds;out.push({id:a.id+'t',date:a.performed_at,title:`Plus longue séance · ${Math.round(a.duration_seconds/60)} min`,sub:SPORT_BY_KEY[a.sport_type]?.label??a.sport_type,verified:integ.status==='verified'})}});return out.reverse().slice(0,30)},[activities]);return <View style={s.root}><View style={s.header}><SensoryPressable event="tap" onPress={()=>router.back()} style={s.back}><ChevronLeft size={21}/></SensoryPressable><View><Text style={s.kicker}>CAREER TIMELINE</Text><Text style={s.h1}>Ta vie sportive</Text></View></View><ScrollView contentContainerStyle={s.content}>{moments.length?moments.map((m,i)=><View key={m.id} style={s.row}><View style={s.lineCol}><View style={[s.dot,{backgroundColor:i===0?'#7C3AED':'#CBD5E1'}]}>{i===0?<Trophy size={13} color="#fff"/>:<Flag size={12} color="#64748B"/>}</View>{i<moments.length-1&&<View style={s.line}/>}</View><View style={s.card}><Text style={s.date}>{new Date(m.date).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</Text><Text style={s.title}>{m.title}</Text><Text style={s.sub}>{m.sub}</Text>{m.verified&&<View style={s.verified}><ShieldCheck size={12} color="#059669"/><Text style={s.verifiedText}>Moment vérifié</Text></View>}</View></View>):<View style={s.empty}><Flame size={26} color="#94A3B8"/><Text style={s.emptyTitle}>Ta timeline va se construire</Text><Text style={s.emptySub}>Les records, longues sorties et grands moments apparaîtront ici automatiquement.</Text></View>}</ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#F4F7FB'},header:{paddingTop:56,paddingHorizontal:16,paddingBottom:12,flexDirection:'row',gap:10,alignItems:'center'},back:{width:38,height:38,borderRadius:13,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',...Shadow.sm},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:'#7C3AED'},h1:{fontSize:24,fontWeight:'900',color:Colors.textPrimary},content:{padding:16,paddingBottom:44},row:{flexDirection:'row',gap:10},lineCol:{width:28,alignItems:'center'},dot:{width:28,height:28,borderRadius:14,alignItems:'center',justifyContent:'center',zIndex:2},line:{width:2,flex:1,backgroundColor:'#E2E8F0',minHeight:62},card:{flex:1,backgroundColor:'#fff',borderRadius:17,padding:13,marginBottom:10,...Shadow.sm},date:{fontSize:8.5,fontWeight:'800',color:Colors.textTertiary,textTransform:'uppercase'},title:{fontSize:13,fontWeight:'900',color:Colors.textPrimary,marginTop:4},sub:{fontSize:10,color:Colors.textSecondary,marginTop:3},verified:{flexDirection:'row',alignItems:'center',gap:4,marginTop:8,alignSelf:'flex-start',backgroundColor:'#ECFDF5',paddingHorizontal:7,paddingVertical:4,borderRadius:99},verifiedText:{fontSize:8.5,fontWeight:'800',color:'#047857'},empty:{padding:28,alignItems:'center',backgroundColor:'#fff',borderRadius:20},emptyTitle:{fontSize:14,fontWeight:'900',color:Colors.textPrimary,marginTop:8},emptySub:{fontSize:10.5,lineHeight:16,color:Colors.textSecondary,textAlign:'center',marginTop:4}})
