import React,{useEffect,useState}from'react'
import{Modal,View,Text,StyleSheet}from'react-native'
import{router}from'expo-router'
import{HybridAvatar2D}from'@/components/v14/HybridAvatar2D'
import{SensoryPressable}from'@/components/v6/SensoryPressable'
import{useV7Economy}from'@/hooks/v7/useV7Economy'
import{useV14Identity}from'@/hooks/v14/useV14Identity'
import{useSession}from'@/hooks/useProfile'
import{FontWeight,Shadow}from'@/constants/theme'
export function AvatarOnboardingGate(){const{userId}=useSession();const{state,ready,setAvatarReady}=useV7Economy();const idState=useV14Identity().state;const[visible,setVisible]=useState(false);useEffect(()=>{if(ready&&userId&&!state.avatarReady)setVisible(true)},[ready,userId,state.avatarReady]);if(!userId)return null;return <Modal visible={visible} transparent animationType="fade"><View style={s.backdrop}><View style={s.card}><Text style={s.kicker}>BIENVENUE DANS HYBRID V15</Text><Text style={s.title}>Crée ton identité sportive</Text><Text style={s.sub}>Un avatar 2D plus travaillé, plus street-sport et moins lisse. Personnalise visage, cheveux, bijoux, tatouages, tenue, accessoires, pose et décor — puis débloque le reste avec tes vraies séances.</Text><HybridAvatar2D equipped={state.equipped} size={250} expression={idState.expression} pose={idState.pose} background={idState.background} silhouette={idState.silhouette} faceShape={idState.faceShape} grain={idState.grain}/><SensoryPressable event="reward" style={s.primary} onPress={()=>{setAvatarReady(true);setVisible(false);setTimeout(()=>router.push('/modals/avatar-studio' as any),100)}}><Text style={s.primaryText}>Créer mon avatar</Text></SensoryPressable><SensoryPressable event="selection" style={s.photo} onPress={()=>{setAvatarReady(true);setVisible(false);setTimeout(()=>router.push('/modals/avatar-photo' as any),100)}}><Text style={s.photoText}>Commencer avec un selfie</Text></SensoryPressable><SensoryPressable event="selection" style={s.secondary} onPress={()=>{setAvatarReady(true);setVisible(false)}}><Text style={s.secondaryText}>Plus tard</Text></SensoryPressable></View></View></Modal>}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:'rgba(17,24,39,.78)',alignItems:'center',justifyContent:'center',padding:22},card:{width:'100%',maxWidth:420,borderRadius:28,padding:22,alignItems:'center',backgroundColor:'#F3EFE7',borderWidth:1,borderColor:'#D5CEC4',...Shadow.lg},kicker:{fontSize:9,color:'#315CFF',fontWeight:FontWeight.extrabold,letterSpacing:1.6},title:{fontSize:27,color:'#111827',fontWeight:FontWeight.extrabold,textAlign:'center',marginTop:7},sub:{fontSize:13,color:'#52627C',textAlign:'center',lineHeight:19,marginTop:8,marginBottom:5},primary:{width:'100%',backgroundColor:'#111827',borderRadius:15,paddingVertical:14,alignItems:'center'},primaryText:{fontWeight:FontWeight.extrabold,color:'#fff'},photo:{width:'100%',marginTop:8,backgroundColor:'#E8EEFF',borderRadius:15,paddingVertical:13,alignItems:'center'},photoText:{color:'#315CFF',fontWeight:FontWeight.extrabold},secondary:{paddingVertical:12},secondaryText:{color:'#64748B',fontWeight:FontWeight.bold}})
