import React from'react'
import{View,Text,StyleSheet}from'react-native'
import{LinearGradient}from'expo-linear-gradient'
import{router}from'expo-router'
import{Coins,Shirt,Sparkles}from'lucide-react-native'
import{HybridAvatar2D}from'@/components/v14/HybridAvatar2D'
import{useV14Identity}from'@/hooks/v14/useV14Identity'
import{SensoryPressable}from'@/components/v6/SensoryPressable'
import{useV7Economy}from'@/hooks/v7/useV7Economy'
import{Colors,FontWeight,Radius,Shadow}from'@/constants/theme'

export function V7PlayerCard(){const{state,level,levelProgress}=useV7Economy();const id=useV14Identity().state;return <LinearGradient colors={['#0B1226','#172554','#312E81']} start={{x:0,y:0}} end={{x:1,y:1}} style={s.card}><View style={s.copy}><View style={s.kicker}><Sparkles size={13} color="#A5B4FC"/><Text style={s.kickerText}>HYBRID IDENTITY</Text></View><Text style={s.title}>Ton athlète évolue avec toi</Text><View style={s.statRow}><View style={s.coin}><Coins size={15} color="#FBBF24"/><Text style={s.coinText}>{state.credits}</Text></View><Text style={s.level}>Niveau {level}</Text></View><View style={s.track}><View style={[s.fill,{width:`${Math.max(4,levelProgress*100)}%`}]} /></View><View style={s.actions}><SensoryPressable event="selection" onPress={()=>router.push('/modals/avatar-studio' as any)} style={s.btn}><Shirt size={15} color="#111827"/><Text style={s.btnText}>Avatar</Text></SensoryPressable><SensoryPressable event="selection" onPress={()=>router.push('/modals/rewards-hub' as any)} style={s.ghost}><Text style={s.ghostText}>Récompenses</Text></SensoryPressable></View></View><View style={s.avatar}><HybridAvatar2D equipped={state.equipped} size={142} expression={id.expression} pose={id.pose} background={id.background} silhouette={id.silhouette} faceShape={id.faceShape} grain={id.grain} compact/></View></LinearGradient>}
const s=StyleSheet.create({card:{marginHorizontal:16,marginTop:10,borderRadius:24,padding:18,minHeight:170,flexDirection:'row',overflow:'hidden',...Shadow.md},copy:{flex:1,zIndex:2},kicker:{flexDirection:'row',alignItems:'center',gap:6},kickerText:{fontSize:9,color:'#C4B5FD',fontWeight:FontWeight.extrabold,letterSpacing:1.3},title:{fontSize:20,lineHeight:24,color:'#fff',fontWeight:FontWeight.extrabold,maxWidth:220,marginTop:8},statRow:{flexDirection:'row',alignItems:'center',gap:10,marginTop:14},coin:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:'rgba(251,191,36,.14)',borderRadius:99,paddingHorizontal:9,paddingVertical:5},coinText:{color:'#FBBF24',fontWeight:FontWeight.extrabold},level:{color:'#D8E1FF',fontSize:12,fontWeight:FontWeight.bold},track:{height:6,borderRadius:99,backgroundColor:'rgba(255,255,255,.14)',marginTop:9,overflow:'hidden',maxWidth:185},fill:{height:'100%',backgroundColor:'#67E8F9',borderRadius:99},actions:{flexDirection:'row',gap:7,marginTop:12},btn:{flexDirection:'row',alignItems:'center',gap:6,backgroundColor:'#fff',borderRadius:12,paddingHorizontal:11,paddingVertical:8},btnText:{fontSize:11,color:'#111827',fontWeight:FontWeight.extrabold},ghost:{borderWidth:1,borderColor:'rgba(255,255,255,.2)',borderRadius:12,paddingHorizontal:10,paddingVertical:8},ghostText:{fontSize:11,color:'#fff',fontWeight:FontWeight.bold},avatar:{position:'absolute',right:-4,bottom:-10}})
