import React,{useMemo,useState}from'react'
import{View,Text,StyleSheet}from'react-native'
import{Target,Flame,Layers3,HeartPulse,Gift,CheckCircle2}from'lucide-react-native'
import{SensoryPressable}from'@/components/v6/SensoryPressable'
import{RewardBurst}from'@/components/v5/RewardBurst'
import{useV7Economy}from'@/hooks/v7/useV7Economy'
import{SPORT_BY_KEY}from'@/constants/sportCatalog'
import type{Activity}from'@/types/database'
import{Colors,FontWeight,Shadow}from'@/constants/theme'
function mondayKey(){const d=new Date();const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d.toISOString().slice(0,10)}
export function V7Quests({activities}:{activities:Activity[]}){const{state,grantGoal}=useV7Economy();const[reward,setReward]=useState<any>(null);const weekKey=mondayKey();const quests=useMemo(()=>{const since=new Date(weekKey+'T00:00:00');const week=activities.filter(a=>new Date(a.performed_at??a.created_at)>=since);const days=new Set(week.map(a=>(a.performed_at??a.created_at).slice(0,10))).size;const families=new Set(week.map(a=>SPORT_BY_KEY[a.sport_type]?.family).filter(Boolean)).size;const hard=week.filter(a=>(a.rpe??0)>=8).length;const easy=week.filter(a=>(a.rpe??5)<=4).length;return[
{id:'move4',title:'4 jours actifs',desc:'Bouge sur 4 jours différents',value:days,target:4,xp:180,credits:120,Icon:Flame,color:'#F97316'},
{id:'hybrid3',title:'Triple Hybrid',desc:'Pratique 3 familles de sports',value:families,target:3,xp:240,credits:180,Icon:Layers3,color:'#8B5CF6',chest:'bronze' as const},
{id:'smart',title:'Charge intelligente',desc:'1 séance intense + 1 séance facile',value:Math.min(hard,1)+Math.min(easy,1),target:2,xp:200,credits:150,Icon:HeartPulse,color:'#10B981'}]},[activities,weekKey]);return <View style={s.wrap}><View style={s.head}><View><Text style={s.kicker}>QUÊTES V7</Text><Text style={s.title}>Joue ta semaine, pas ta santé</Text></View><Target size={20} color={Colors.electric}/></View>{quests.map(q=>{const id=`${weekKey}:${q.id}`,done=q.value>=q.target,claimed=state.claimedGoals.includes(id),pct=Math.min(1,q.value/q.target);return <SensoryPressable key={q.id} event={done&&!claimed?'reward':'selection'} onPress={()=>{if(!done||claimed)return;if(grantGoal(id,q.xp,q.credits,(q as any).chest))setReward(q)}} style={[s.card,done&&!claimed&&{borderColor:q.color+'66'}]}><View style={[s.icon,{backgroundColor:q.color+'16'}]}>{claimed?<CheckCircle2 size={18} color={q.color}/>:<q.Icon size={18} color={q.color}/>}</View><View style={{flex:1}}><View style={s.top}><Text style={s.qTitle}>{q.title}</Text><Text style={[s.reward,{color:q.color}]}>{claimed?'RÉCUPÉRÉ':done?'RÉCUPÉRER':`+${q.xp} XP`}</Text></View><Text style={s.desc}>{q.desc}</Text><View style={s.bar}><View style={[s.fill,{width:`${Math.max(4,pct*100)}%`,backgroundColor:q.color}]}/></View><Text style={s.progress}>{Math.min(q.value,q.target)}/{q.target} · +{q.credits} crédits{(q as any).chest?' · capsule':''}</Text></View></SensoryPressable>})}<RewardBurst visible={!!reward} title={reward?.title??'Quête terminée'} subtitle={`+${reward?.credits??0} crédits${reward?.chest?' · Capsule Bronze':''}`} xp={reward?.xp??0} onClose={()=>setReward(null)}/></View>}
const s=StyleSheet.create({wrap:{paddingHorizontal:16,marginBottom:16,gap:8},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:2},kicker:{fontSize:8.5,color:Colors.electric,fontWeight:FontWeight.extrabold,letterSpacing:1.2},title:{fontSize:15,color:Colors.textPrimary,fontWeight:FontWeight.extrabold,marginTop:2},card:{backgroundColor:'#fff',borderRadius:17,padding:12,flexDirection:'row',gap:10,alignItems:'center',borderWidth:1,borderColor:Colors.borderLight,...Shadow.sm},icon:{width:40,height:40,borderRadius:13,alignItems:'center',justifyContent:'center'},top:{flexDirection:'row',justifyContent:'space-between',gap:8},qTitle:{fontSize:11.5,color:Colors.textPrimary,fontWeight:FontWeight.extrabold},reward:{fontSize:8.5,fontWeight:FontWeight.extrabold},desc:{fontSize:9.5,color:Colors.textTertiary,marginTop:2},bar:{height:5,backgroundColor:Colors.bgAlt,borderRadius:99,overflow:'hidden',marginTop:7},fill:{height:'100%',borderRadius:99},progress:{fontSize:8.5,color:Colors.textTertiary,marginTop:4,fontWeight:FontWeight.bold}})
