-- Hybrid.App V9 — Track Everything
-- Incremental migration. Apply after the previous Hybrid migrations on a development project first.

-- 1) Connected providers / sync health
create table if not exists public.connected_sources (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  status text not null default 'disconnected' check (status in ('disconnected','pending','connected','error')),
  provider_user_id text,
  scopes jsonb not null default '[]'::jsonb,
  last_sync_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,provider)
);
create index if not exists connected_sources_user_idx on public.connected_sources(user_id);

-- 2) Hybrid native tracked sessions.
create table if not exists public.tracking_sessions_v9 (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  sport_type text not null,
  tracker_mode text not null,
  status text not null default 'running' check(status in ('running','paused','finished','discarded')),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  elapsed_seconds integer not null default 0,
  distance_km numeric not null default 0,
  elevation_m numeric not null default 0,
  rpe integer check(rpe between 1 and 10),
  source_device text,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists tracking_sessions_v9_user_started_idx on public.tracking_sessions_v9(user_id,started_at desc);

create table if not exists public.tracking_points_v9 (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.tracking_sessions_v9(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  altitude_m double precision,
  speed_mps double precision,
  accuracy_m double precision,
  recorded_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists tracking_points_v9_session_idx on public.tracking_points_v9(session_id,recorded_at);

create table if not exists public.tracking_events_v9 (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.tracking_sessions_v9(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  at_seconds integer not null default 0,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists tracking_events_v9_session_idx on public.tracking_events_v9(session_id,at_seconds);

create table if not exists public.activity_splits_v9 (
  id uuid primary key default gen_random_uuid(),
  activity_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  split_index integer not null,
  distance_km numeric not null,
  duration_seconds numeric not null,
  pace_seconds_per_km numeric,
  heart_rate integer,
  elevation_delta_m numeric,
  created_at timestamptz not null default now(),
  unique(activity_id,split_index)
);
create index if not exists activity_splits_v9_activity_idx on public.activity_splits_v9(activity_id,split_index);

-- 3) Cross-provider dedupe.
create table if not exists public.external_activity_links_v9 (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_id uuid not null,
  provider text not null,
  external_id text not null,
  fingerprint text,
  imported_at timestamptz not null default now(),
  unique(user_id,provider,external_id)
);
create index if not exists external_activity_links_v9_fingerprint_idx on public.external_activity_links_v9(user_id,fingerprint) where fingerprint is not null;

-- 4) Routes/segments
create table if not exists public.personal_route_efforts_v9 (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_id uuid,
  sport_type text not null,
  route_hash text,
  distance_km numeric not null,
  duration_seconds integer not null,
  avg_pace_seconds_per_km numeric,
  avg_speed_kph numeric,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists personal_route_efforts_v9_user_sport_idx on public.personal_route_efforts_v9(user_id,sport_type,occurred_at desc);

-- RLS
alter table public.connected_sources enable row level security;
alter table public.tracking_sessions_v9 enable row level security;
alter table public.tracking_points_v9 enable row level security;
alter table public.tracking_events_v9 enable row level security;
alter table public.activity_splits_v9 enable row level security;
alter table public.external_activity_links_v9 enable row level security;
alter table public.personal_route_efforts_v9 enable row level security;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['connected_sources','tracking_sessions_v9','tracking_points_v9','tracking_events_v9','activity_splits_v9','external_activity_links_v9','personal_route_efforts_v9'] LOOP
    EXECUTE format('drop policy if exists %I on public.%I', t||'_self', t);
    EXECUTE format('create policy %I on public.%I for all using(auth.uid()=user_id) with check(auth.uid()=user_id)', t||'_self', t);
  END LOOP;
END $$;
