-- Hybrid.App V7 — production sync layer for avatar/economy/rewards.
-- Apply only after reviewing against your current Supabase schema.
create table if not exists public.player_economy (
  user_id uuid primary key references auth.users(id) on delete cascade,
  credits integer not null default 250 check (credits >= 0),
  identity_xp integer not null default 0 check (identity_xp >= 0),
  daily_streak integer not null default 0,
  last_daily date,
  active_boost jsonb,
  updated_at timestamptz not null default now()
);
create table if not exists public.player_cosmetics (
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id text not null,
  acquired_at timestamptz not null default now(),
  source text not null default 'reward',
  primary key(user_id,item_id)
);
create table if not exists public.player_equipment_loadout (
  user_id uuid primary key references auth.users(id) on delete cascade,
  equipped jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create table if not exists public.reward_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reward_key text not null,
  reward_type text not null,
  xp integer not null default 0,
  credits integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(user_id,reward_key)
);
create index if not exists reward_ledger_user_created_idx on public.reward_ledger(user_id,created_at desc);
alter table public.player_economy enable row level security;
alter table public.player_cosmetics enable row level security;
alter table public.player_equipment_loadout enable row level security;
alter table public.reward_ledger enable row level security;
drop policy if exists "economy self read" on public.player_economy;
create policy "economy self read" on public.player_economy for select using(auth.uid()=user_id);
drop policy if exists "cosmetics self read" on public.player_cosmetics;
create policy "cosmetics self read" on public.player_cosmetics for select using(auth.uid()=user_id);
drop policy if exists "loadout self read" on public.player_equipment_loadout;
create policy "loadout self read" on public.player_equipment_loadout for select using(auth.uid()=user_id);
drop policy if exists "ledger self read" on public.reward_ledger;
create policy "ledger self read" on public.reward_ledger for select using(auth.uid()=user_id);
-- IMPORTANT: in production, writes for credits/xp should go through a trusted RPC/Edge Function,
-- not arbitrary client updates, to prevent reward/leaderboard cheating.
